/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import function.AdminInfo;
import function.StudentInfo;
import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import model.Admin;
import model.Student;
import util.DbUtil;
import util.StringUtil;

/**
 *
 * @author ZP Chen
 */
public class AdminInfoAdd extends javax.swing.JInternalFrame {

    /**
     * Creates new form StuInfoMaintainInternalFrame
     */
    String adminSex;//管理员性别
    DbUtil dbUtil = new DbUtil();
    AdminInfo adminInfo = new AdminInfo();
    public AdminInfoAdd() {
        initComponents();
        adminSex = this.adminManRadioButton.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        adminInfoAddButton = new javax.swing.JButton();
        adminResetButton = new javax.swing.JButton();
        adminManRadioButton = new javax.swing.JRadioButton();
        adminWomanRadioButton = new javax.swing.JRadioButton();
        adminNameText = new javax.swing.JTextField();
        adminLogInNameText = new javax.swing.JTextField();
        adminPhoneText = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        adminInterestText = new javax.swing.JTextField();
        adminLogInPasswordText = new javax.swing.JPasswordField();
        adminLogInPasswordConfirmText = new javax.swing.JPasswordField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("jRadioButtonMenuItem2");

        setClosable(true);
        setTitle("管理员信息添加");
        setToolTipText("");

        jLabel2.setFont(new java.awt.Font("华文行楷", 0, 24)); // NOI18N
        jLabel2.setText("姓名*");

        jLabel3.setFont(new java.awt.Font("华文行楷", 0, 24)); // NOI18N
        jLabel3.setText("性别*");

        jLabel4.setFont(new java.awt.Font("华文行楷", 0, 24)); // NOI18N
        jLabel4.setText("手机*");

        jLabel5.setFont(new java.awt.Font("华文行楷", 0, 24)); // NOI18N
        jLabel5.setText("用户名*");

        jLabel6.setFont(new java.awt.Font("华文行楷", 0, 24)); // NOI18N
        jLabel6.setText("密码*");

        jLabel7.setFont(new java.awt.Font("华文行楷", 0, 24)); // NOI18N
        jLabel7.setText("再次确认*");

        jLabel9.setBackground(new java.awt.Color(255, 0, 0));
        jLabel9.setFont(new java.awt.Font("华文行楷", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("填写要求：1、除兴趣一栏可选外其余均为必填！");

        adminInfoAddButton.setFont(new java.awt.Font("华文行楷", 0, 18)); // NOI18N
        adminInfoAddButton.setText("添加");
        adminInfoAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminInfoAddButtonActionPerformed(evt);
            }
        });

        adminResetButton.setFont(new java.awt.Font("华文行楷", 0, 18)); // NOI18N
        adminResetButton.setText("重置");
        adminResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminResetButtonActionPerformed(evt);
            }
        });

        adminManRadioButton.setSelected(true);
        adminManRadioButton.setText("男");
        adminManRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminManRadioButtonActionPerformed(evt);
            }
        });

        adminWomanRadioButton.setText("女");
        adminWomanRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminWomanRadioButtonActionPerformed(evt);
            }
        });

        adminNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminNameTextActionPerformed(evt);
            }
        });

        adminLogInNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminLogInNameTextActionPerformed(evt);
            }
        });

        adminPhoneText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminPhoneTextActionPerformed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/admin.png"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("华文行楷", 0, 24)); // NOI18N
        jLabel10.setText("兴趣");

        adminInterestText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminInterestTextActionPerformed(evt);
            }
        });

        adminLogInPasswordText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminLogInPasswordTextActionPerformed(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(255, 0, 0));
        jLabel12.setFont(new java.awt.Font("华文行楷", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setText("2、手机号为11位纯数字，如13358878188");

        jLabel13.setBackground(new java.awt.Color(255, 0, 0));
        jLabel13.setFont(new java.awt.Font("华文行楷", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 0, 0));
        jLabel13.setText("3、密码不能低于6位");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(adminPhoneText)
                        .addComponent(adminLogInNameText)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(adminInfoAddButton)
                            .addGap(152, 152, 152)
                            .addComponent(adminResetButton))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(adminManRadioButton)
                            .addGap(18, 18, 18)
                            .addComponent(adminWomanRadioButton))
                        .addComponent(adminLogInPasswordConfirmText)
                        .addComponent(adminNameText)
                        .addComponent(adminLogInPasswordText, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(adminInterestText, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel13)
                        .addComponent(jLabel12)))
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(adminNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(adminManRadioButton)
                    .addComponent(adminWomanRadioButton))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(adminPhoneText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(adminLogInNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(adminLogInPasswordText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(adminLogInPasswordConfirmText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminInterestText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminInfoAddButton)
                    .addComponent(adminResetButton))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adminInfoAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminInfoAddButtonActionPerformed
        // TODO add your handling code here:
           //添加新管理员信息
        try{
            adminInfoAddActionPerformed(evt);
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_adminInfoAddButtonActionPerformed

    private void adminManRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminManRadioButtonActionPerformed
        // TODO add your handling code here:
        if(!this.adminManRadioButton.isSelected()){
            this.adminManRadioButton.setSelected(true);
        }
        this.adminWomanRadioButton.setSelected(false);
        adminSex = this.adminManRadioButton.getText();
        //System.out.println(adminSex);        
    }//GEN-LAST:event_adminManRadioButtonActionPerformed

    private void adminNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminNameTextActionPerformed

    private void adminLogInNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminLogInNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminLogInNameTextActionPerformed

    private void adminPhoneTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminPhoneTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminPhoneTextActionPerformed

    private void adminInterestTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminInterestTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminInterestTextActionPerformed

    private void adminLogInPasswordTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminLogInPasswordTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminLogInPasswordTextActionPerformed

    private void adminWomanRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminWomanRadioButtonActionPerformed
        // TODO add your handling code here:
        if(!this.adminWomanRadioButton.isSelected()){
            this.adminWomanRadioButton.setSelected(true);
        }
        this.adminManRadioButton.setSelected(false);
        adminSex = this.adminWomanRadioButton.getText();
        //System.out.println(adminSex); 
    }//GEN-LAST:event_adminWomanRadioButtonActionPerformed

    private void adminResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminResetButtonActionPerformed
        // TODO add your handling code here:
        resetAdminInfo();//重置管理员信息方法
    }//GEN-LAST:event_adminResetButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminInfoAddButton;
    private javax.swing.JTextField adminInterestText;
    private javax.swing.JTextField adminLogInNameText;
    private javax.swing.JPasswordField adminLogInPasswordConfirmText;
    private javax.swing.JPasswordField adminLogInPasswordText;
    private javax.swing.JRadioButton adminManRadioButton;
    private javax.swing.JTextField adminNameText;
    private javax.swing.JTextField adminPhoneText;
    private javax.swing.JButton adminResetButton;
    private javax.swing.JRadioButton adminWomanRadioButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    // End of variables declaration//GEN-END:variables

    private void adminInfoAddActionPerformed(ActionEvent evt) throws SQLException, Exception {//添加管理员信息
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        String adminName = this.adminNameText.getText();
        String adminLogInName = this.adminLogInNameText.getText();
        String adminPhone = this.adminPhoneText.getText();
        String adminRemark = this.adminInterestText.getText();
        String adminLogInPassword = new String(this.adminLogInPasswordText.getPassword());
        String adminLogInPasswordConfirm = new String(this.adminLogInPasswordConfirmText.getPassword());
        if(StringUtil.isEmpty(adminName)){
            JOptionPane.showMessageDialog(null,"姓名不能为空！");
            return;
        }
        if(StringUtil.isEmpty(adminPhone)){
            JOptionPane.showMessageDialog(null,"手机不能为空！");
            return;
        }
        if(StringUtil.isEmpty(adminLogInName)){
            JOptionPane.showMessageDialog(null,"用户名不能为空！");
            return;
        }
        if(StringUtil.isEmpty(adminLogInPassword)){
            JOptionPane.showMessageDialog(null,"密码不能为空！");
            return;
        }
        if(StringUtil.isEmpty(adminLogInPasswordConfirm)){
            JOptionPane.showMessageDialog(null,"再次确认密码不能为空！");
            return;
        }
        if(adminPhone.length() != 11){
            JOptionPane.showMessageDialog(null,"手机号位数不为11位！");
            return;
        } 
        if(!StringUtil.isAllNumber(adminPhone)){
            JOptionPane.showMessageDialog(null,"手机号不为纯数字！");
            return;
        } 
        if(adminLogInPassword.length() < 6){
            JOptionPane.showMessageDialog(null,"密码强度过低，请重新输入！");
            return;
        } 
        if(!adminLogInPassword.equals(adminLogInPasswordConfirm)){
            JOptionPane.showMessageDialog(null,"两次密码不匹配，请重新输入！");
            return;
        }
        Connection con = null;
        con = dbUtil.getConnection();
        if(adminInfo.checkExist(con, adminLogInName)){
            JOptionPane.showMessageDialog(null,"当前用户名已存在，请重新输入！");
            return;
        }
        Admin admin = new Admin(adminName,adminSex,adminPhone,adminLogInName,adminLogInPassword,adminRemark);
        try{
            con = dbUtil.getConnection();
            int result = adminInfo.adminInfoAdd(con,admin);
            if(result == 1){
                con = dbUtil.getConnection();
                int adminID = adminInfo.returnAdminID(con);
                JOptionPane.showMessageDialog(null,"管理员添加成功！您的管理员编号为"+String.valueOf(adminID)+"！");
                resetAdminInfo();//重置管理员信息所有栏
                return;
            }
            else{
                JOptionPane.showMessageDialog(null,"管理员添加失败！");
                return;
            }
        }catch (Exception e)
        {
            e.printStackTrace();
        }
    }

    private void resetAdminInfo() {//重置管理员信息
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        this.adminNameText.setText("");
        this.adminPhoneText.setText("");
        this.adminInterestText.setText("");
        this.adminLogInNameText.setText("");
        this.adminLogInPasswordText.setText("");
        this.adminLogInPasswordConfirmText.setText("");
        this.adminManRadioButton.setSelected(true);
        this.adminWomanRadioButton.setSelected(false);
        adminSex = this.adminManRadioButton.getText();
    }
}
