/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import function.BorrowInfo;
import function.EquipmentInfo;
import function.StudentInfo;
import function.TeacherInfo;
import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import util.DbUtil;
import util.StringUtil;

/**
 *
 * @author ZP Chen
 */
public class Borrow extends javax.swing.JInternalFrame {

    /**
     * Creates new form Borrow
     */
    private String type = "学生";
    StudentInfo studentInfo = new StudentInfo();
    TeacherInfo teacherInfo = new TeacherInfo();
    EquipmentInfo equipmentInfo = new EquipmentInfo();
    DbUtil dbUtil = new DbUtil();
    BorrowInfo borrowInfo = new BorrowInfo();
    public Borrow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        stuRadioButton = new javax.swing.JRadioButton();
        teaRadioButton = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        IDText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        equipIDText = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        borrowButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("借用器材");

        jLabel3.setFont(new java.awt.Font("华文行楷", 0, 24)); // NOI18N
        jLabel3.setText("类型");

        stuRadioButton.setSelected(true);
        stuRadioButton.setText("学生");
        stuRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stuRadioButtonActionPerformed(evt);
            }
        });

        teaRadioButton.setText("老师");
        teaRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teaRadioButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("华文行楷", 0, 24)); // NOI18N
        jLabel1.setText("学号/教工号");

        IDText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDTextActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("华文行楷", 0, 24)); // NOI18N
        jLabel2.setText("器材编号");

        equipIDText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equipIDTextActionPerformed(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(255, 0, 0));
        jLabel9.setFont(new java.awt.Font("华文行楷", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("借用规则：1、被列入黑名单一周之内无法借用器材；");

        jLabel10.setBackground(new java.awt.Color(255, 0, 0));
        jLabel10.setFont(new java.awt.Font("华文行楷", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("2、老师最多可借5样，学生最多可借3样；");

        borrowButton.setFont(new java.awt.Font("华文行楷", 0, 18)); // NOI18N
        borrowButton.setText("借用");
        borrowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrowButtonActionPerformed(evt);
            }
        });

        resetButton.setFont(new java.awt.Font("华文行楷", 0, 18)); // NOI18N
        resetButton.setText("重置");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/register.png"))); // NOI18N

        jLabel11.setBackground(new java.awt.Color(255, 0, 0));
        jLabel11.setFont(new java.awt.Font("华文行楷", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setText("3、每次借用期限学生（7天）/老师（15天）。");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(IDText, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(borrowButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(resetButton))
                            .addComponent(equipIDText, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(stuRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(teaRadioButton)
                        .addGap(174, 174, 174)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(123, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10))
                .addGap(15, 15, 15))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(stuRadioButton)
                            .addComponent(teaRadioButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(IDText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(equipIDText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(borrowButton)
                            .addComponent(resetButton))))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stuRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stuRadioButtonActionPerformed
        // TODO add your handling code here:
        if(!this.stuRadioButton.isSelected()){
            this.stuRadioButton.setSelected(true);
        }
        this.teaRadioButton.setSelected(false);
        type = this.stuRadioButton.getText();
    }//GEN-LAST:event_stuRadioButtonActionPerformed

    private void teaRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teaRadioButtonActionPerformed
        // TODO add your handling code here:
        if(!this.teaRadioButton.isSelected()){
            this.teaRadioButton.setSelected(true);
        }
        this.stuRadioButton.setSelected(false);
        type = this.teaRadioButton.getText();
    }//GEN-LAST:event_teaRadioButtonActionPerformed

    private void IDTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDTextActionPerformed

    private void equipIDTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equipIDTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_equipIDTextActionPerformed

    private void borrowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrowButtonActionPerformed

        // TODO add your handling code here:
        //借用操作
        String ID = this.IDText.getText();
        String equipID = this.equipIDText.getText();
        try{
            if(check(ID,equipID)){//检查本次借用是否合法
                borrowActionPerformed(evt,ID,equipID);//检查合法，执行借用器材操作
            }
        }catch(Exception e){
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_borrowButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // TODO add your handling code here:
        //重置操作
        resetValues();
    }//GEN-LAST:event_resetButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDText;
    private javax.swing.JButton borrowButton;
    private javax.swing.JTextField equipIDText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton resetButton;
    private javax.swing.JRadioButton stuRadioButton;
    private javax.swing.JRadioButton teaRadioButton;
    // End of variables declaration//GEN-END:variables

    private void resetValues() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        this.IDText.setText("");
        this.equipIDText.setText("");
    }

    private void borrowActionPerformed(ActionEvent evt, String ID, String equipID) throws SQLException, Exception {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        Connection con =null;
        if(type.equals("学生")){//执行学生借用器材操作
            con = dbUtil.getConnection();
            int result = borrowInfo.studentBorrow(con, ID, equipID);
            if(result ==1){
                JOptionPane.showMessageDialog(null, "借用成功！");
                con = dbUtil.getConnection();
                equipmentInfo.setBorrowed(con, equipID);//置器材被借用操作
                resetValues();
            }
            else{
                JOptionPane.showMessageDialog(null, "借用失败！");
                return;
            }
        }
        else{//执行老师借用器材操作
            con = dbUtil.getConnection();
            int result = borrowInfo.teacherBorrow(con, ID, equipID);
            if(result ==1){
                JOptionPane.showMessageDialog(null, "借用成功！");
                con = dbUtil.getConnection();
                equipmentInfo.setBorrowed(con, equipID);//置器材被借用操作
                resetValues();
            }
            else{
                JOptionPane.showMessageDialog(null, "借用失败！");
                return;
            }
        }
    }

    private boolean check(String ID, String equipID) throws Exception {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        if(type.equals("学生")){
            if(StringUtil.isEmpty(ID)){
                JOptionPane.showMessageDialog(null, "学号不能为空！");
                return false;
            }
        }
        else{
            if(StringUtil.isEmpty(ID)){
                JOptionPane.showMessageDialog(null, "教工号不能为空！");
                return false;
            }
        }
        Connection con = null;
        if(StringUtil.isEmpty(equipID)){
            JOptionPane.showMessageDialog(null, "器材编号不能为空！");
            return false;
        }
        if(type.equals("学生")){
            if(ID.length() != 14){
                JOptionPane.showMessageDialog(null, "请输入14位学号！");
                return false;
            }
            try{
                con = dbUtil.getConnection();
                if(!studentInfo.isStuIDExist(con, ID)){
                    JOptionPane.showMessageDialog(null, "当前学号不存在！");
                    return false;
                }
            }catch(Exception e){
                e.printStackTrace();
            }
            try{
                con = dbUtil.getConnection();
                if(studentInfo.isStuIDBlack(con, ID)){
                    JOptionPane.showMessageDialog(null, "当前用户为黑名单，无法借用！");
                    return false;
                }
            }catch(Exception e){
                e.printStackTrace();
            }
            try{
                con = dbUtil.getConnection();
                if(studentInfo.countEquipBorrow(con, ID) == 3){
                    JOptionPane.showMessageDialog(null, "当前学生已经达到可借用器材数量！");
                    return false;
                }
            }catch(Exception e){
                e.printStackTrace();
            }
        }
        else{
            if(ID.length() != 11){
                JOptionPane.showMessageDialog(null, "请输入11位教工号！");
                return false;
            }
            try{
                con = dbUtil.getConnection();
                if(!teacherInfo.isTeaIDExist(con, ID)){
                    JOptionPane.showMessageDialog(null, "当前教工号不存在！");
                    return false;
                }
            }catch(Exception e){
                e.printStackTrace();
            }
            try{
                con = dbUtil.getConnection();
                if(teacherInfo.isTeaIDBlack(con, ID)){
                    JOptionPane.showMessageDialog(null, "当前用户为黑名单，无法借用！");
                    return false;
                }
            }catch(Exception e){
                e.printStackTrace();
            }
            try{
                con = dbUtil.getConnection();
                if(teacherInfo.countEquipBorrow(con, ID) == 5){
                    JOptionPane.showMessageDialog(null, "当前老师已经达到可借用器材数量！");
                    return false;
                }
            }catch(Exception e){
                e.printStackTrace();
            }
        }
        try{
            con = dbUtil.getConnection();
            if(!equipmentInfo.isEquipIDExist(con, equipID)){
                JOptionPane.showMessageDialog(null, "当前器材编号不存在！");
                return false;
            }
        }catch(Exception e){
            e.printStackTrace();
        }
        try{
            con = dbUtil.getConnection();
            if(!equipmentInfo.isAvailable(con, equipID)){
                JOptionPane.showMessageDialog(null, "当前器材已报废！");
                return false;
            }
        }catch(Exception e){
            e.printStackTrace();
        }
        try{
            con = dbUtil.getConnection();
            if(equipmentInfo.isBorrowed(con, equipID)){
                JOptionPane.showMessageDialog(null, "当前器材已被借走！");
                return false;
            }
        }catch(Exception e){
            e.printStackTrace();
        }
        return true;
    }
}
