/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import function.EquipmentInfo;
import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import util.DbUtil;
import util.StringUtil;
/**
 *
 * @author ZP Chen
 */
public class EquipScrap extends javax.swing.JInternalFrame {

    /**
     * Creates new form EquipScrapInternalFrame
     */
    EquipmentInfo equipmentInfo = new EquipmentInfo();
    DbUtil dbUtil = new DbUtil();
    boolean isScrap;//报废或撤销报废标志
    public EquipScrap() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        equipIDText = new javax.swing.JTextField();
        scrapButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();

        setClosable(true);
        setTitle("器材报废登记");

        jLabel1.setFont(new java.awt.Font("华文行楷", 0, 24)); // NOI18N
        jLabel1.setText("器材编号");

        equipIDText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equipIDTextActionPerformed(evt);
            }
        });

        scrapButton.setFont(new java.awt.Font("华文行楷", 0, 18)); // NOI18N
        scrapButton.setText("报废");
        scrapButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scrapButtonActionPerformed(evt);
            }
        });

        resetButton.setFont(new java.awt.Font("华文行楷", 0, 18)); // NOI18N
        resetButton.setText("重置");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/dustbin.png"))); // NOI18N

        cancelButton.setFont(new java.awt.Font("华文行楷", 0, 18)); // NOI18N
        cancelButton.setText("撤销");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(scrapButton)
                        .addGap(41, 41, 41)
                        .addComponent(cancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(resetButton))
                    .addComponent(equipIDText, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(equipIDText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(scrapButton)
                            .addComponent(resetButton)
                            .addComponent(cancelButton))))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void equipIDTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equipIDTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_equipIDTextActionPerformed

    private void scrapButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scrapButtonActionPerformed
        try {
            // TODO add your handling code here:
            //报废操作
            scrapActionPerformed(evt,true);
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_scrapButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // TODO add your handling code here:
        //重置操作
        resetValues();
    }//GEN-LAST:event_resetButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            //撤销报废操作
            scrapActionPerformed(evt,false);
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_cancelButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField equipIDText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton scrapButton;
    // End of variables declaration//GEN-END:variables

    private void resetValues() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        this.equipIDText.setText("");
    }

    private void scrapActionPerformed(ActionEvent evt,boolean isScrap) throws Exception {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        String equipID = this.equipIDText.getText();
        if(StringUtil.isEmpty(equipID)){
            JOptionPane.showMessageDialog(null, "器材编号不能为空！");
            return;
        }
        if(!StringUtil.isAllNumber(equipID)){
            JOptionPane.showMessageDialog(null, "器材编号不合法！");
            return;
        }
        Connection con = dbUtil.getConnection();
        if(!equipmentInfo.isEquipIDExist(con, equipID)){
            JOptionPane.showMessageDialog(null, "当前器材编号不存在！");
            return;
        }
        con = dbUtil.getConnection();
        String currentIsAvailable = equipmentInfo.returnIsAvailable(con, equipID);
        if(isScrap && currentIsAvailable.equals("No")){
            JOptionPane.showMessageDialog(null,"当前器材已报废！");
            return;
        }
        if(!isScrap && currentIsAvailable.equals("Yes")){
            JOptionPane.showMessageDialog(null,"当前器材未报废！");
            return;
        }
        try{
            con = dbUtil.getConnection();
            int result = equipmentInfo.scrap(con, equipID, isScrap);
            if(result == 1){
                if(isScrap ){
                    JOptionPane.showMessageDialog(null,"报废成功！");
                }
                else{
                    JOptionPane.showMessageDialog(null,"撤销报废成功！");
                }
                resetValues();//重置报废信息所有栏
            }
            else{
                if(!isScrap){
                    JOptionPane.showMessageDialog(null,"报废失败！");
                }
                else{
                    JOptionPane.showMessageDialog(null,"撤销报废失败！");
                }
            }
        }catch (Exception e)
        {
            e.printStackTrace();
        }
    }
}
