/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import function.EquipmentInfo;
import function.MaintainInfo;
import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Maintain;
import util.DbUtil;
import util.StringUtil;

/**
 *
 * @author ZP Chen
 */
public class EquipmentMaintain extends javax.swing.JInternalFrame {

    /**
     * Creates new form EquipmentMaintainInternalFrame
     */
    DbUtil dbUtil = new DbUtil();
    MaintainInfo maintainInfo = new MaintainInfo();
    EquipmentInfo equipmentInfo = new EquipmentInfo();
    public EquipmentMaintain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        equipID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        maintainExpense = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        maintainReason = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();

        setClosable(true);
        setTitle("器材维修登记");

        jLabel1.setFont(new java.awt.Font("华文行楷", 0, 24)); // NOI18N
        jLabel1.setText("器材编号");

        equipID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equipIDActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("华文行楷", 0, 24)); // NOI18N
        jLabel2.setText("维修费用");

        maintainExpense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maintainExpenseActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("华文行楷", 0, 24)); // NOI18N
        jLabel3.setText("维修原因");

        maintainReason.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maintainReasonActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/maintenance.png"))); // NOI18N

        addButton.setFont(new java.awt.Font("华文行楷", 0, 18)); // NOI18N
        addButton.setText("添加");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        resetButton.setFont(new java.awt.Font("华文行楷", 0, 18)); // NOI18N
        resetButton.setText("重置");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(maintainExpense, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(equipID, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(resetButton))
                            .addComponent(maintainReason, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(equipID, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(maintainExpense, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(maintainReason, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(resetButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void equipIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equipIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_equipIDActionPerformed

    private void maintainExpenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maintainExpenseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maintainExpenseActionPerformed

    private void maintainReasonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maintainReasonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maintainReasonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed

        try {
            // TODO add your handling code here:
            //添加维修器材信息
            addActionPerformed(evt);
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // TODO add your handling code here:
        //维修器材信息重置
        resetValues();
    }//GEN-LAST:event_resetButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JTextField equipID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField maintainExpense;
    private javax.swing.JTextField maintainReason;
    private javax.swing.JButton resetButton;
    // End of variables declaration//GEN-END:variables

    private void resetValues() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        this.equipID.setText("");
        this.maintainExpense.setText("");
        this.maintainReason.setText("");
    }

    private void addActionPerformed(ActionEvent evt) throws Exception {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        String equipID = this.equipID.getText();
        String maintainExpense = this.maintainExpense.getText();
        String maintainReason = this.maintainReason.getText();
        if(StringUtil.isEmpty(equipID)){
            JOptionPane.showMessageDialog(null, "器材编号不能为空！");
            return;
        }
        if(StringUtil.isEmpty(maintainExpense)){
            JOptionPane.showMessageDialog(null, "维修费用不能为空！");
            return;
        }
        if(StringUtil.isEmpty(maintainReason)){
            JOptionPane.showMessageDialog(null, "维修原因不能为空！");
            return;
        }
        if(!StringUtil.isAllNumber(equipID)){
            JOptionPane.showMessageDialog(null, "请输入合法的器材编号！");
            return;
        }
        if(!StringUtil.isFloat(maintainExpense)){
            JOptionPane.showMessageDialog(null, "请输入合法的维修费用！");
            return;
        }
        Connection con = null;
        con = dbUtil.getConnection();
        if(!equipmentInfo.isEquipIDExist(con, equipID)){
            JOptionPane.showMessageDialog(null, "当前器材编号不存在！");
            return;
        }
        try{
            con = dbUtil.getConnection();
            Maintain maintain = new Maintain(equipID,maintainExpense,maintainReason);
            int result = maintainInfo.maintainInfoAdd(con, maintain);
            if(result == 1){
                JOptionPane.showMessageDialog(null,"维修信息添加成功！");
                resetValues();//重置维修信息所有栏
            }
            else{
                JOptionPane.showMessageDialog(null,"维修信息添加失败！");
            }
        }catch (Exception e)
        {
            e.printStackTrace();
        }
    }
}
