/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import java.awt.event.ActionEvent;
import java.sql.Connection;
import javax.swing.JOptionPane;
import model.Admin;
import util.DbUtil;
import util.StringUtil;
import function.LogInVerify;

/**
 *
 * @author ZP Chen
 */
public class LogOnFrame extends javax.swing.JFrame {

    /**
     * Creates new form LogOnFrame
     */
    public LogOnFrame() {
        initComponents();
        this.setLocation(350,200);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        logInBut = new javax.swing.JButton();
        resetBut = new javax.swing.JButton();
        adminNameText = new javax.swing.JTextField();
        adminPasswordText = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("运动器材管理系统登录界面");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("华文行楷", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/dumbbell.png"))); // NOI18N
        jLabel1.setText("运动器材管理系统");

        jLabel2.setFont(new java.awt.Font("华文行楷", 0, 36)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/bussiness-man.png"))); // NOI18N
        jLabel2.setText("用户名");

        jLabel3.setFont(new java.awt.Font("华文行楷", 0, 36)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/key.png"))); // NOI18N
        jLabel3.setText("密码");

        logInBut.setFont(new java.awt.Font("华文行楷", 0, 24)); // NOI18N
        logInBut.setLabel("登录");
        logInBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logInButActionPerformed(evt);
            }
        });

        resetBut.setFont(new java.awt.Font("华文行楷", 0, 24)); // NOI18N
        resetBut.setLabel("重置");
        resetBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButActionPerformed(evt);
            }
        });

        adminNameText.setToolTipText("");
        adminNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminNameTextActionPerformed(evt);
            }
        });

        adminPasswordText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminPasswordTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(adminNameText)
                            .addComponent(adminPasswordText, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(logInBut)
                        .addGap(108, 108, 108)
                        .addComponent(resetBut)
                        .addGap(103, 103, 103)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addComponent(adminNameText, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(adminPasswordText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logInBut)
                    .addComponent(resetBut))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logInButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logInButActionPerformed
        // TODO add your handling code here:
        //登录操作
        try{
        logInActionPerformed(evt);}
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_logInButActionPerformed

    private void adminNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminNameTextActionPerformed

    private void resetButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButActionPerformed
        // TODO add your handling code here:
        //重置操作
        resetActionPerformed(evt);
    }//GEN-LAST:event_resetButActionPerformed

    private void adminPasswordTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminPasswordTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminPasswordTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogOnFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogOnFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogOnFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogOnFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogOnFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adminNameText;
    private javax.swing.JPasswordField adminPasswordText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton logInBut;
    private javax.swing.JButton resetBut;
    // End of variables declaration//GEN-END:variables

    private DbUtil dbUtil = new DbUtil();
    private LogInVerify userVerify = new LogInVerify();
    
    
    private void resetActionPerformed(ActionEvent evt) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        //重置操作
        this.adminNameText.setText("");
        this.adminPasswordText.setText("");
    }

    private void logInActionPerformed(ActionEvent evt) throws Exception {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        //登录操作
        String adminName = this.adminNameText.getText();
        String adminPassword = new String(this.adminPasswordText.getPassword());
        if(StringUtil.isEmpty(adminName)){
            JOptionPane.showMessageDialog(null,"用户名不能为空！");
            return;
        }
        if(StringUtil.isEmpty(adminPassword)){
            JOptionPane.showMessageDialog(null,"密码不能为空！");
            return;
        }
        Admin admin = new Admin(adminName,adminPassword);
        Connection con = null;
        con = dbUtil.getConnection();
        Admin currentAdmin = userVerify.Login(con, admin);
        dbUtil.closeConnection(con);
        if(currentAdmin != null){
            dispose();//销毁登录窗口
            MainFrame mainFrame = new MainFrame();
            mainFrame.setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(null,"用户名或密码错误！");
            return;
        }
        
    }
}
