/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import java.awt.Frame;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author ZP Chen
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form AdminMainFrame
     */
    public MainFrame() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);//窗口最大化
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem6 = new javax.swing.JMenuItem();
        Table = new javax.swing.JPanel();
        MenuBar = new javax.swing.JMenuBar();
        InfoAdd = new javax.swing.JMenu();
        stuInfoAddMenu = new javax.swing.JMenuItem();
        teaInfoAddMenu = new javax.swing.JMenuItem();
        adminInfoAddMenu = new javax.swing.JMenuItem();
        blackListMenu = new javax.swing.JMenuItem();
        InfoMaintain = new javax.swing.JMenu();
        stuInfoMaintainMenu = new javax.swing.JMenuItem();
        teaInfoMaintainMenu = new javax.swing.JMenuItem();
        adminInfoMaintainMenu = new javax.swing.JMenuItem();
        Transcations = new javax.swing.JMenu();
        borrowMenu = new javax.swing.JMenuItem();
        returnMenu = new javax.swing.JMenuItem();
        equipmentInRegisterMenu = new javax.swing.JMenuItem();
        maintainInfoMenu = new javax.swing.JMenuItem();
        equipmentScrapMenu = new javax.swing.JMenuItem();
        blackListHistorySearchMenu = new javax.swing.JMenu();
        equipSearchMenu = new javax.swing.JMenuItem();
        borrowHistorySearchMenu = new javax.swing.JMenuItem();
        maintainHistorySearchMenu = new javax.swing.JMenuItem();
        blackListSearchMenu = new javax.swing.JMenuItem();
        SysSetting = new javax.swing.JMenu();
        MoreMenu = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        ExitMenu = new javax.swing.JMenuItem();

        jMenuItem6.setText("jMenuItem6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("管理员主界面");

        Table.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout TableLayout = new javax.swing.GroupLayout(Table);
        Table.setLayout(TableLayout);
        TableLayout.setHorizontalGroup(
            TableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 432, Short.MAX_VALUE)
        );
        TableLayout.setVerticalGroup(
            TableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 287, Short.MAX_VALUE)
        );

        InfoAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/add2.png"))); // NOI18N
        InfoAdd.setText("人员信息添加");

        stuInfoAddMenu.setText("学生信息添加");
        stuInfoAddMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stuInfoAddMenuActionPerformed(evt);
            }
        });
        InfoAdd.add(stuInfoAddMenu);

        teaInfoAddMenu.setText("老师信息添加");
        teaInfoAddMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teaInfoAddMenuActionPerformed(evt);
            }
        });
        InfoAdd.add(teaInfoAddMenu);

        adminInfoAddMenu.setText("管理员信息添加");
        adminInfoAddMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminInfoAddMenuActionPerformed(evt);
            }
        });
        InfoAdd.add(adminInfoAddMenu);

        blackListMenu.setText("黑名单");
        blackListMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blackListMenuActionPerformed(evt);
            }
        });
        InfoAdd.add(blackListMenu);

        MenuBar.add(InfoAdd);

        InfoMaintain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/tools.png"))); // NOI18N
        InfoMaintain.setText("人员信息维护");

        stuInfoMaintainMenu.setText("学生信息维护");
        stuInfoMaintainMenu.setToolTipText("");
        stuInfoMaintainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stuInfoMaintainMenuActionPerformed(evt);
            }
        });
        InfoMaintain.add(stuInfoMaintainMenu);

        teaInfoMaintainMenu.setText("老师信息维护");
        teaInfoMaintainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teaInfoMaintainMenuActionPerformed(evt);
            }
        });
        InfoMaintain.add(teaInfoMaintainMenu);

        adminInfoMaintainMenu.setText("管理员信息维护");
        adminInfoMaintainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminInfoMaintainMenuActionPerformed(evt);
            }
        });
        InfoMaintain.add(adminInfoMaintainMenu);

        MenuBar.add(InfoMaintain);

        Transcations.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/employee.png"))); // NOI18N
        Transcations.setText("业务办理");

        borrowMenu.setText("借用器材");
        borrowMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrowMenuActionPerformed(evt);
            }
        });
        Transcations.add(borrowMenu);

        returnMenu.setText("归还器材");
        returnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnMenuActionPerformed(evt);
            }
        });
        Transcations.add(returnMenu);

        equipmentInRegisterMenu.setText("器材入库登记");
        equipmentInRegisterMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equipmentInRegisterMenuActionPerformed(evt);
            }
        });
        Transcations.add(equipmentInRegisterMenu);

        maintainInfoMenu.setText("器材维修登记");
        maintainInfoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maintainInfoMenuActionPerformed(evt);
            }
        });
        Transcations.add(maintainInfoMenu);

        equipmentScrapMenu.setText("器材报废登记");
        equipmentScrapMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equipmentScrapMenuActionPerformed(evt);
            }
        });
        Transcations.add(equipmentScrapMenu);

        MenuBar.add(Transcations);

        blackListHistorySearchMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/loupe.png"))); // NOI18N
        blackListHistorySearchMenu.setText("报表查询");

        equipSearchMenu.setText("器材信息查询");
        equipSearchMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equipSearchMenuActionPerformed(evt);
            }
        });
        blackListHistorySearchMenu.add(equipSearchMenu);

        borrowHistorySearchMenu.setText("器材借用历史查询");
        borrowHistorySearchMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrowHistorySearchMenuActionPerformed(evt);
            }
        });
        blackListHistorySearchMenu.add(borrowHistorySearchMenu);

        maintainHistorySearchMenu.setText("器材维修历史查询");
        maintainHistorySearchMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maintainHistorySearchMenuActionPerformed(evt);
            }
        });
        blackListHistorySearchMenu.add(maintainHistorySearchMenu);

        blackListSearchMenu.setText("黑名单查询");
        blackListSearchMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blackListSearchMenuActionPerformed(evt);
            }
        });
        blackListHistorySearchMenu.add(blackListSearchMenu);

        MenuBar.add(blackListHistorySearchMenu);

        SysSetting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/system.png"))); // NOI18N
        SysSetting.setText("系统设置");
        SysSetting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SysSettingActionPerformed(evt);
            }
        });

        MoreMenu.setText("More");
        MoreMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoreMenuActionPerformed(evt);
            }
        });
        SysSetting.add(MoreMenu);

        jMenuItem1.setText("致谢");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        SysSetting.add(jMenuItem1);

        ExitMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        ExitMenu.setText("Exit");
        ExitMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitMenuActionPerformed(evt);
            }
        });
        SysSetting.add(ExitMenu);

        MenuBar.add(SysSetting);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Table, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Table, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stuInfoAddMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stuInfoAddMenuActionPerformed
        // TODO add your handling code here:
        //创建学生信息维护新窗口并加入到面板中
        StuInfoAdd stuInfoAddInternalFrame = new StuInfoAdd();      
        stuInfoAddInternalFrame.setVisible(true);
        Table.add(stuInfoAddInternalFrame);
    }//GEN-LAST:event_stuInfoAddMenuActionPerformed

    private void MoreMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoreMenuActionPerformed
        // TODO add your handling code here:
        //创建More新窗口并加入到面板中
        More moreInternalFrame = new More();
        moreInternalFrame.setVisible(true);
        Table.add(moreInternalFrame);
    }//GEN-LAST:event_MoreMenuActionPerformed

    private void SysSettingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SysSettingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SysSettingActionPerformed

    private void ExitMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitMenuActionPerformed
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(null, "确定退出系统？");
        if(result == 0){//确定退出系统
            dispose();//销毁当前界面
        }
    }//GEN-LAST:event_ExitMenuActionPerformed

    private void borrowMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrowMenuActionPerformed
        // TODO add your handling code here:
        //创建借用器材窗口并加入到面板中
        Borrow borrow = new Borrow();
        borrow.setVisible(true);
        Table.add(borrow);
    }//GEN-LAST:event_borrowMenuActionPerformed

    private void teaInfoAddMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teaInfoAddMenuActionPerformed
        // TODO add your handling code here:
        //创建老师信息添加新窗口并加入到面板中
        TeaInfoAdd teaInfoAddInternalFrame = new TeaInfoAdd();
        teaInfoAddInternalFrame.setVisible(true);
        Table.add(teaInfoAddInternalFrame);
    }//GEN-LAST:event_teaInfoAddMenuActionPerformed

    private void adminInfoAddMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminInfoAddMenuActionPerformed
        // TODO add your handling code here:
        //创建管理员信息添加新窗口并加入到面板中
        AdminInfoAdd adminInfoAddInternalFrame = new AdminInfoAdd();
        adminInfoAddInternalFrame.setVisible(true);
        Table.add(adminInfoAddInternalFrame);
    }//GEN-LAST:event_adminInfoAddMenuActionPerformed

    private void blackListMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blackListMenuActionPerformed
        // TODO add your handling code here:
        //创建黑名单窗口并加入到面板中
        BlackList blackListInternalFrame = new BlackList();
        blackListInternalFrame.setVisible(true);
        Table.add(blackListInternalFrame);
    }//GEN-LAST:event_blackListMenuActionPerformed

    private void equipmentInRegisterMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equipmentInRegisterMenuActionPerformed
        // TODO add your handling code here:
        //创建器材入库登记窗口并加入到面板中
        EquipmentInRegister equipmentInRegister = new EquipmentInRegister();
        equipmentInRegister.setVisible(true);
        Table.add(equipmentInRegister);
    }//GEN-LAST:event_equipmentInRegisterMenuActionPerformed

    private void maintainInfoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maintainInfoMenuActionPerformed
        // TODO add your handling code here:
        //创建器材维修登记窗口并加入到面板中
        EquipmentMaintain equipmentMaintainInternalFrame = new EquipmentMaintain();
        equipmentMaintainInternalFrame.setVisible(true);
        Table.add(equipmentMaintainInternalFrame);
    }//GEN-LAST:event_maintainInfoMenuActionPerformed

    private void equipmentScrapMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equipmentScrapMenuActionPerformed
        // TODO add your handling code here:
        //创建器材报废登记窗口并加入到面板中
        EquipScrap equipScrapInternalFrame = new EquipScrap();
        equipScrapInternalFrame.setVisible(true);
        Table.add(equipScrapInternalFrame);
    }//GEN-LAST:event_equipmentScrapMenuActionPerformed

    private void equipSearchMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equipSearchMenuActionPerformed
        // TODO add your handling code here:
        //创建器材信息查询窗口并加入到面板中
        ShowEquipmentSituation  showEquipmentSituationInteanalFrame = new ShowEquipmentSituation();
        showEquipmentSituationInteanalFrame.setVisible(true);
        Table.add(showEquipmentSituationInteanalFrame);
    }//GEN-LAST:event_equipSearchMenuActionPerformed

    private void stuInfoMaintainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stuInfoMaintainMenuActionPerformed
        // TODO add your handling code here:
        //创建学生信息维护窗口并加入到面板中
        ShowStudentInfo  showStudentInfoInteanalFrame = new ShowStudentInfo();
        showStudentInfoInteanalFrame.setVisible(true);
        Table.add(showStudentInfoInteanalFrame);
    }//GEN-LAST:event_stuInfoMaintainMenuActionPerformed

    private void teaInfoMaintainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teaInfoMaintainMenuActionPerformed
        // TODO add your handling code here:
        //创建老师信息维护窗口并加入到面板中
        ShowTeacherInfo  showTeacherInfoInteanalFrame = new ShowTeacherInfo();
        showTeacherInfoInteanalFrame.setVisible(true);
        Table.add(showTeacherInfoInteanalFrame);
    }//GEN-LAST:event_teaInfoMaintainMenuActionPerformed

    private void adminInfoMaintainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminInfoMaintainMenuActionPerformed
        // TODO add your handling code here:
         //创建管理员信息维护窗口并加入到面板中
        ShowAdminInfo  showAdminInfoInteanalFrame = new ShowAdminInfo();
        showAdminInfoInteanalFrame.setVisible(true);
        Table.add(showAdminInfoInteanalFrame);
    }//GEN-LAST:event_adminInfoMaintainMenuActionPerformed

    private void returnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnMenuActionPerformed
        // TODO add your handling code here:
        Return ret = new Return();
        ret.setVisible(true);
        Table.add(ret);
    }//GEN-LAST:event_returnMenuActionPerformed

    private void maintainHistorySearchMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maintainHistorySearchMenuActionPerformed
        // TODO add your handling code here:
        //创建器材维修历史查询窗口并加入到面板中
        ShowEquipmentMaintainHistory  showEquipmentMaintainHistory = new ShowEquipmentMaintainHistory();
        showEquipmentMaintainHistory.setVisible(true);
        Table.add(showEquipmentMaintainHistory);
    }//GEN-LAST:event_maintainHistorySearchMenuActionPerformed

    private void borrowHistorySearchMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrowHistorySearchMenuActionPerformed
        // TODO add your handling code here:
        //创建借用历史查询窗口并加入到面板中
        ShowBorrowHistory  showBorrowHistory = new ShowBorrowHistory();
        showBorrowHistory.setVisible(true);
        Table.add(showBorrowHistory);
    }//GEN-LAST:event_borrowHistorySearchMenuActionPerformed

    private void blackListSearchMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blackListSearchMenuActionPerformed
        // TODO add your handling code here:
        //创建黑名单查询窗口并加入到面板中
        ShowBlackHistory  showBlackHistory = new ShowBlackHistory();
        showBlackHistory.setVisible(true);
        Table.add(showBlackHistory);
    }//GEN-LAST:event_blackListSearchMenuActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        //创建致谢窗口并加入到面板中
        Thanks thanks = new Thanks();
        thanks.setVisible(true);
        Table.add(thanks);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ExitMenu;
    private javax.swing.JMenu InfoAdd;
    private javax.swing.JMenu InfoMaintain;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenuItem MoreMenu;
    private javax.swing.JMenu SysSetting;
    private javax.swing.JPanel Table;
    private javax.swing.JMenu Transcations;
    private javax.swing.JMenuItem adminInfoAddMenu;
    private javax.swing.JMenuItem adminInfoMaintainMenu;
    private javax.swing.JMenu blackListHistorySearchMenu;
    private javax.swing.JMenuItem blackListMenu;
    private javax.swing.JMenuItem blackListSearchMenu;
    private javax.swing.JMenuItem borrowHistorySearchMenu;
    private javax.swing.JMenuItem borrowMenu;
    private javax.swing.JMenuItem equipSearchMenu;
    private javax.swing.JMenuItem equipmentInRegisterMenu;
    private javax.swing.JMenuItem equipmentScrapMenu;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem maintainHistorySearchMenu;
    private javax.swing.JMenuItem maintainInfoMenu;
    private javax.swing.JMenuItem returnMenu;
    private javax.swing.JMenuItem stuInfoAddMenu;
    private javax.swing.JMenuItem stuInfoMaintainMenu;
    private javax.swing.JMenuItem teaInfoAddMenu;
    private javax.swing.JMenuItem teaInfoMaintainMenu;
    // End of variables declaration//GEN-END:variables
}
