/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import function.BlackInfo;
import function.EquipmentInfo;
import function.ReturnInfo;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import util.DbUtil;
import util.StringUtil;

/**
 *
 * @author ZP Chen
 */
public class Return extends javax.swing.JInternalFrame {

    /**
     * Creates new form Return
     */
    private String type = "学生";
    ReturnInfo returnInfo = new ReturnInfo();
    DbUtil dbUtil = new DbUtil();
    BlackInfo blackInfo = new BlackInfo();
    EquipmentInfo equipmentInfo = new EquipmentInfo();
    public Return() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        stuRadioButton = new javax.swing.JRadioButton();
        teaRadioButton = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        IDText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        equipIDText = new javax.swing.JTextField();
        returnButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("归还器材");

        jLabel3.setFont(new java.awt.Font("华文行楷", 0, 24)); // NOI18N
        jLabel3.setText("类型");

        stuRadioButton.setSelected(true);
        stuRadioButton.setText("学生");
        stuRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stuRadioButtonActionPerformed(evt);
            }
        });

        teaRadioButton.setText("老师");
        teaRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teaRadioButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("华文行楷", 0, 24)); // NOI18N
        jLabel1.setText("学号/教工号");

        IDText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDTextActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("华文行楷", 0, 24)); // NOI18N
        jLabel2.setText("器材编号");

        equipIDText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equipIDTextActionPerformed(evt);
            }
        });

        returnButton.setFont(new java.awt.Font("华文行楷", 0, 18)); // NOI18N
        returnButton.setText("归还");
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });

        resetButton.setFont(new java.awt.Font("华文行楷", 0, 18)); // NOI18N
        resetButton.setText("重置");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/return.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(equipIDText, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(IDText, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(returnButton)
                            .addGap(152, 152, 152)
                            .addComponent(resetButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(stuRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(teaRadioButton)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(stuRadioButton)
                            .addComponent(teaRadioButton))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(IDText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(equipIDText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(returnButton)
                            .addComponent(resetButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel4)))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stuRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stuRadioButtonActionPerformed
        // TODO add your handling code here:
        if(!this.stuRadioButton.isSelected()){
            this.stuRadioButton.setSelected(true);
        }
        this.teaRadioButton.setSelected(false);
        type = this.stuRadioButton.getText();
    }//GEN-LAST:event_stuRadioButtonActionPerformed

    private void teaRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teaRadioButtonActionPerformed
        // TODO add your handling code here:
        if(!this.teaRadioButton.isSelected()){
            this.teaRadioButton.setSelected(true);
        }
        this.stuRadioButton.setSelected(false);
        type = this.teaRadioButton.getText();
    }//GEN-LAST:event_teaRadioButtonActionPerformed

    private void IDTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDTextActionPerformed

    private void equipIDTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equipIDTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_equipIDTextActionPerformed

    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed

        // TODO add your handling code here:
        String ID = this.IDText.getText();
        String equipID = this.equipIDText.getText();
        try {
            if(check(ID,equipID)){//检查本次归还信息的合法性
                Connection con = dbUtil.getConnection();
                if(type.equals("学生")){
                    int returnResult = returnInfo.studentReturnOperation(con, ID, equipID);
                    if(returnResult == 1){
                        con = dbUtil.getConnection();
                        int inTimeResult = returnInfo.studentReturnCheckInTime(con, ID, equipID);
                        if(inTimeResult < 0){
                            con = dbUtil.getConnection();
                            blackInfo.updateBlackList(con, ID, "学生");
                            con = dbUtil.getConnection();
                            equipmentInfo.setReturn(con, equipID);
                            JOptionPane.showMessageDialog(null, "归还成功！本次归还已逾期"+String.valueOf(-inTimeResult)+"天！系统已自动将该用户列入黑名单！");
                        }
                        else{
                            con = dbUtil.getConnection();
                            equipmentInfo.setReturn(con, equipID);
                            JOptionPane.showMessageDialog(null, "归还成功！");
                        }
                        resetValues();
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "归还失败！");
                        return;
                    }
                }
                if(type.equals("老师")){
                    int returnResult = returnInfo.teacherReturnOperation(con, ID, equipID);
                    if(returnResult == 1){
                        con = dbUtil.getConnection();
                        int inTimeResult = returnInfo.teacherReturnCheckInTime(con, ID, equipID);
                        if(inTimeResult < 0){
                            con = dbUtil.getConnection();
                            blackInfo.updateBlackList(con, ID, "老师");
                            con = dbUtil.getConnection();
                            equipmentInfo.setReturn(con, equipID);
                            JOptionPane.showMessageDialog(null, "归还成功！本次归还已逾期"+String.valueOf(-inTimeResult)+"天！系统已自动将该用户列入黑名单！");
                        }
                        else{
                            con = dbUtil.getConnection();
                            equipmentInfo.setReturn(con, equipID);
                            JOptionPane.showMessageDialog(null, "归还成功！");
                        }
                        resetValues();
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "归还失败！");
                        return;
                    }
                }
            }
        }catch(Exception e){
            e.printStackTrace();
        }

    }//GEN-LAST:event_returnButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // TODO add your handling code here:
        //重置操作
        resetValues();
    }//GEN-LAST:event_resetButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDText;
    private javax.swing.JTextField equipIDText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton returnButton;
    private javax.swing.JRadioButton stuRadioButton;
    private javax.swing.JRadioButton teaRadioButton;
    // End of variables declaration//GEN-END:variables

    private void resetValues() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        this.IDText.setText("");
        this.equipIDText.setText("");
    }

    private boolean check(String ID, String equipID) throws SQLException, Exception {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        if(StringUtil.isEmpty(ID)){
            if(type.equals("学生")){
                JOptionPane.showMessageDialog(null, "学号不能为空！");
                return false;
            }
            else{
                JOptionPane.showMessageDialog(null, "教工号不能为空！");
                return false;
            }
        }
        if(StringUtil.isEmpty(equipID)){
            JOptionPane.showMessageDialog(null, "器材编号不能为空！");
            return false;
        }
        if(type.equals("学生")){
            if(!StringUtil.isAllNumber(ID)){
                JOptionPane.showMessageDialog(null, "请输入合法的学号！");
                return false;
            }
            if(ID.length() != 14){
                JOptionPane.showMessageDialog(null, "请输入14位的学号！");
                return false;
            }
        }
        if(type.equals("老师")){
            if(!StringUtil.isAllNumber(ID)){
                JOptionPane.showMessageDialog(null, "请输入合法的教工号！");
                return false;
            }
            if(ID.length() != 11){
                JOptionPane.showMessageDialog(null, "请输入11位的教工号！");
                return false;
            }
        }
        if(!StringUtil.isAllNumber(equipID)){
            JOptionPane.showMessageDialog(null, "请输入合法的器材编号！");
            return false;
        }
        Connection con = dbUtil.getConnection();
        if(type.equals("老师")){
            if(!returnInfo.teacherReturnCheck(con, ID, equipID)){
                JOptionPane.showMessageDialog(null, "当前借用记录未找到，请输入正确的信息！");
                return false;
            }
            con = dbUtil.getConnection();
            if(!returnInfo.equipStateTeacherCheck(con, ID, equipID)){
                JOptionPane.showMessageDialog(null, "当前器材已归还，请勿重复操作！");
                return false;
            }
        }
        if(type.equals("学生")){
            if(!returnInfo.studentReturnCheck(con, ID, equipID)){
                JOptionPane.showMessageDialog(null, "当前借用记录未找到，请输入正确的信息！");
                return false;
            }
            con = dbUtil.getConnection();
            if(!returnInfo.equipStateStudentCheck(con, ID, equipID)){
                JOptionPane.showMessageDialog(null, "当前器材已归还，请勿重复操作！");
                return false;
            }
        }
        return true;
    }
}
