/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;
import model.Equipment;
import function.EquipmentInfo;
import util.DbUtil;
import java.sql.Connection;
import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JOptionPane;
import util.StringUtil;
/**
 *
 * @author ZP Chen
 */
public class ShowEquipmentSituation extends javax.swing.JInternalFrame {

    /**
     * Creates new form ShowBorrowInternalFrame
     */
    private String type = "按名称";
    DbUtil dbUtil = new DbUtil();
    EquipmentInfo equipmentInfo = new EquipmentInfo();
    public ShowEquipmentSituation() {
        initComponents();
        this.initTable(new Equipment());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        accordIDButton = new javax.swing.JRadioButton();
        accordNameButton = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        IDOrNameText = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        equipTableScrollPane = new javax.swing.JScrollPane();
        equipTable = new javax.swing.JTable();
        searchButton1 = new javax.swing.JButton();

        setClosable(true);
        setTitle("器材信息查询");

        jLabel3.setFont(new java.awt.Font("华文行楷", 0, 24)); // NOI18N
        jLabel3.setText("查询类型");

        accordIDButton.setSelected(true);
        accordIDButton.setText("按名称");
        accordIDButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accordIDButtonActionPerformed(evt);
            }
        });

        accordNameButton.setText("按编号");
        accordNameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accordNameButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("华文行楷", 0, 24)); // NOI18N
        jLabel1.setText("编号/名称");

        IDOrNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDOrNameTextActionPerformed(evt);
            }
        });

        searchButton.setFont(new java.awt.Font("华文行楷", 0, 18)); // NOI18N
        searchButton.setText("查询");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        equipTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        equipTable.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        equipTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "器材编号", "名称", "描述", "是否被借", "是否可用", "单价/元", "入库日期", "报废日期"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        equipTable.setGridColor(new java.awt.Color(204, 204, 204));
        equipTableScrollPane.setViewportView(equipTable);

        searchButton1.setFont(new java.awt.Font("华文行楷", 0, 18)); // NOI18N
        searchButton1.setText("查看所有");
        searchButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(accordIDButton)
                                .addGap(18, 18, 18)
                                .addComponent(accordNameButton)
                                .addGap(18, 18, 18)
                                .addComponent(searchButton)
                                .addGap(18, 18, 18)
                                .addComponent(searchButton1))
                            .addComponent(IDOrNameText)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(equipTableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 754, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(accordIDButton)
                    .addComponent(accordNameButton)
                    .addComponent(searchButton)
                    .addComponent(searchButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(IDOrNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(equipTableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void accordIDButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accordIDButtonActionPerformed
        // TODO add your handling code here:
        if(!this.accordIDButton.isSelected()){
            this.accordIDButton.setSelected(true);
        }
        this.accordNameButton.setSelected(false);
        type = this.accordIDButton.getText();
    }//GEN-LAST:event_accordIDButtonActionPerformed

    private void accordNameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accordNameButtonActionPerformed
        // TODO add your handling code here:
        if(!this.accordNameButton.isSelected()){
            this.accordNameButton.setSelected(true);
        }
        this.accordIDButton.setSelected(false);
        type = this.accordNameButton.getText();
    }//GEN-LAST:event_accordNameButtonActionPerformed

    private void IDOrNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDOrNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDOrNameTextActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed

        // TODO add your handling code here:
        //根据编号或名称查询
        Equipment equip = new Equipment();
        String idOrNameText = this.IDOrNameText.getText();
        if(StringUtil.isEmpty(idOrNameText)){
            JOptionPane.showMessageDialog(null,"输入不能为空！");
            return;
        }
        if(type.equals("按名称")){
            equip.setEquipName(idOrNameText);
        }
        if(type.equals("按编号") && !StringUtil.isAllNumber(idOrNameText)){
            JOptionPane.showMessageDialog(null,"请输入正确格式的编号！");
            return;
        }
        this.updateTable(equip);
        resetSearchValues();
    }//GEN-LAST:event_searchButtonActionPerformed

    private void searchButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButton1ActionPerformed
        // TODO add your handling code here:
        this.initTable(new Equipment());
    }//GEN-LAST:event_searchButton1ActionPerformed

    //初始化表格
    private void initTable(Equipment equip){
        DefaultTableModel dtm = (DefaultTableModel)equipTable.getModel();
        dtm.setRowCount(0);
        Connection con = null;
        try{
            con = dbUtil.getConnection();
            ResultSet rs;
            rs = equipmentInfo.listByName(con,equip);
            while(rs.next()){
                Vector vec = new Vector();
                vec.add(rs.getInt("equipID"));
                vec.add(rs.getString("equipName"));
                vec.add(rs.getString("equipDescription"));
                vec.add(rs.getString("isBorrowed"));
                vec.add(rs.getString("isAvailable"));
                vec.add(rs.getFloat("unitPrice"));
                vec.add(rs.getString("registerDate").substring(0, 10));
                String scrapDate = rs.getString("scrapDate");
                if(StringUtil.isNotEmpty(scrapDate)){
                    scrapDate = scrapDate.substring(0,10);
                }
                vec.add(scrapDate);
                dtm.addRow(vec);
            }
            con.close();
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    //更新表格
    private void updateTable(Equipment equip){
        DefaultTableModel dtm = (DefaultTableModel)equipTable.getModel();
        dtm.setRowCount(0);
        Connection con = null;
        try{
            con = dbUtil.getConnection();
            ResultSet rs;
            if(type.equals("按编号")){
                rs = equipmentInfo.listByID(con,this.IDOrNameText.getText());
            }
            else{
                rs = equipmentInfo.listByName(con,equip);
            }
            int rsIsEmptyFlag = 0;
            while(rs.next()){
                rsIsEmptyFlag =1;
                Vector vec = new Vector();
                vec.add(rs.getInt("equipID"));
                vec.add(rs.getString("equipName"));
                vec.add(rs.getString("equipDescription"));
                vec.add(rs.getString("isBorrowed"));
                vec.add(rs.getString("isAvailable"));
                vec.add(rs.getFloat("unitPrice"));
                vec.add(rs.getString("registerDate").substring(0, 10));
                String scrapDate = rs.getString("scrapDate");
                if(StringUtil.isNotEmpty(scrapDate)){
                    scrapDate = scrapDate.substring(0,10);
                }
                vec.add(scrapDate);
                dtm.addRow(vec);
            }
            con.close();
            if(rsIsEmptyFlag == 0){
                JOptionPane.showMessageDialog(null, "查无此器材！");
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDOrNameText;
    private javax.swing.JRadioButton accordIDButton;
    private javax.swing.JRadioButton accordNameButton;
    private javax.swing.JTable equipTable;
    private javax.swing.JScrollPane equipTableScrollPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton searchButton;
    private javax.swing.JButton searchButton1;
    // End of variables declaration//GEN-END:variables

    private void resetSearchValues() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        this.IDOrNameText.setText("");
        this.accordIDButton.setSelected(true);
        this.accordNameButton.setSelected(false);
        type = this.accordIDButton.getText();
    }
}
