/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;
import function.EquipmentInfo;
import function.StudentInfo;
import java.awt.event.ActionEvent;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Equipment;
import model.Student;
import util.DbUtil;
import util.StringUtil;
/**
 *
 * @author ZP Chen
 */
public class ShowStudentInfo extends javax.swing.JInternalFrame {

    /**
     * Creates new form ShowBorrowInternalFrame
     */
    private String type = "按姓名";
    DbUtil dbUtil = new DbUtil();
    StudentInfo studentInfo = new StudentInfo();
    public ShowStudentInfo() {
        initComponents();
        this.initTable(new Student());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        accordIDButton = new javax.swing.JRadioButton();
        accordNameButton = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        IDOrNameText = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        stuTableScrollPane = new javax.swing.JScrollPane();
        stuTable = new javax.swing.JTable();
        searchButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        stuIDText = new javax.swing.JTextField();
        stuNameText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        stuCollegeText = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        stuDepartmentText = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        stuPhoneText = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        stuRemarkText = new javax.swing.JTextField();
        deleteButton = new javax.swing.JButton();
        modifyButton = new javax.swing.JButton();

        setClosable(true);
        setTitle("学生信息维护");
        setToolTipText("");

        jLabel3.setFont(new java.awt.Font("华文行楷", 0, 24)); // NOI18N
        jLabel3.setText("查询类型");

        accordIDButton.setSelected(true);
        accordIDButton.setText("按姓名");
        accordIDButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accordIDButtonActionPerformed(evt);
            }
        });

        accordNameButton.setText("按学号");
        accordNameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accordNameButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("华文行楷", 0, 24)); // NOI18N
        jLabel1.setText("姓名/学号");

        IDOrNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDOrNameTextActionPerformed(evt);
            }
        });

        searchButton.setFont(new java.awt.Font("华文行楷", 0, 18)); // NOI18N
        searchButton.setText("查询");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        stuTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        stuTable.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        stuTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "学号", "姓名", "性别", "学院", "系", "类型", "手机", "兴趣"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        stuTable.setGridColor(new java.awt.Color(204, 204, 204));
        stuTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                stuTableMousePressed(evt);
            }
        });
        stuTableScrollPane.setViewportView(stuTable);
        if (stuTable.getColumnModel().getColumnCount() > 0) {
            stuTable.getColumnModel().getColumn(6).setResizable(false);
            stuTable.getColumnModel().getColumn(7).setResizable(false);
        }

        searchButton1.setFont(new java.awt.Font("华文行楷", 0, 18)); // NOI18N
        searchButton1.setText("查看所有");
        searchButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButton1ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("华文行楷", 0, 24)); // NOI18N
        jLabel4.setText("学号");

        jLabel6.setFont(new java.awt.Font("华文行楷", 0, 24)); // NOI18N
        jLabel6.setText("姓名");

        stuIDText.setEditable(false);
        stuIDText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stuIDTextActionPerformed(evt);
            }
        });

        stuNameText.setEditable(false);
        stuNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stuNameTextActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("华文行楷", 0, 24)); // NOI18N
        jLabel5.setText("学院*");

        stuCollegeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stuCollegeTextActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("华文行楷", 0, 24)); // NOI18N
        jLabel7.setText("系*");

        stuDepartmentText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stuDepartmentTextActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("华文行楷", 0, 24)); // NOI18N
        jLabel8.setText("手机*");

        stuPhoneText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stuPhoneTextActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("华文行楷", 0, 24)); // NOI18N
        jLabel9.setText("兴趣");

        stuRemarkText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stuRemarkTextActionPerformed(evt);
            }
        });

        deleteButton.setFont(new java.awt.Font("华文行楷", 0, 18)); // NOI18N
        deleteButton.setText("删除");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        modifyButton.setFont(new java.awt.Font("华文行楷", 0, 18)); // NOI18N
        modifyButton.setText("修改");
        modifyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(stuIDText, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(stuCollegeText, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(stuPhoneText, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(stuNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(stuDepartmentText, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(stuRemarkText, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(modifyButton)
                .addGap(70, 70, 70)
                .addComponent(deleteButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel6)
                    .addComponent(stuNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(stuIDText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel7)
                    .addComponent(stuDepartmentText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(stuCollegeText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel9)
                    .addComponent(stuRemarkText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(stuPhoneText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteButton)
                    .addComponent(modifyButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(accordIDButton)
                                .addGap(18, 18, 18)
                                .addComponent(accordNameButton)
                                .addGap(18, 18, 18)
                                .addComponent(searchButton)
                                .addGap(18, 18, 18)
                                .addComponent(searchButton1))
                            .addComponent(IDOrNameText)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(stuTableScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 754, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(accordIDButton)
                    .addComponent(accordNameButton)
                    .addComponent(searchButton)
                    .addComponent(searchButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(IDOrNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(stuTableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void accordIDButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accordIDButtonActionPerformed
        // TODO add your handling code here:
        if(!this.accordIDButton.isSelected()){
            this.accordIDButton.setSelected(true);
        }
        this.accordNameButton.setSelected(false);
        type = this.accordIDButton.getText();
    }//GEN-LAST:event_accordIDButtonActionPerformed

    private void accordNameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accordNameButtonActionPerformed
        // TODO add your handling code here:
        if(!this.accordNameButton.isSelected()){
            this.accordNameButton.setSelected(true);
        }
        this.accordIDButton.setSelected(false);
        type = this.accordNameButton.getText();
    }//GEN-LAST:event_accordNameButtonActionPerformed

    private void IDOrNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDOrNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDOrNameTextActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed

        // TODO add your handling code here:
        //根据学号或姓名查询
        Student stu = new Student();
        String idOrNameText = this.IDOrNameText.getText();
        if(StringUtil.isEmpty(idOrNameText)){
            JOptionPane.showMessageDialog(null,"输入不能为空！");
            return;
        }
        if(type.equals("按姓名")){
            stu.setStuName(idOrNameText);
        }
        if(type.equals("按学号") && !StringUtil.isAllNumber(idOrNameText)){
            JOptionPane.showMessageDialog(null,"请输入正确格式的学号！");
            return;
        }
        if(type.equals("按学号") && idOrNameText.length() != 14){
            JOptionPane.showMessageDialog(null,"请输入14位的学号！");
            return;
        }
        this.updateTable(stu);
        resetSearchValues();
    }//GEN-LAST:event_searchButtonActionPerformed

    private void searchButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButton1ActionPerformed
        // TODO add your handling code here:
        this.initTable(new Student());
    }//GEN-LAST:event_searchButton1ActionPerformed

    private void stuIDTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stuIDTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stuIDTextActionPerformed

    private void stuNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stuNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stuNameTextActionPerformed

    private void stuCollegeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stuCollegeTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stuCollegeTextActionPerformed

    private void stuDepartmentTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stuDepartmentTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stuDepartmentTextActionPerformed

    private void stuPhoneTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stuPhoneTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stuPhoneTextActionPerformed

    private void stuRemarkTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stuRemarkTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stuRemarkTextActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        try {
            // TODO add your handling code here:
            //删除操作
            deleteActionPerformed(evt);
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void modifyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyButtonActionPerformed
        try {
            // TODO add your handling code here:
            //学生信息修改操作
            modifyActionPerformed(evt);
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_modifyButtonActionPerformed

    private void stuTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stuTableMousePressed
        // TODO add your handling code here:
        //表格单击显示数据
        stuTableMousePressedAction(evt);
    }//GEN-LAST:event_stuTableMousePressed

    //初始化表格
    private void initTable(Student stu){
        DefaultTableModel dtm = (DefaultTableModel)stuTable.getModel();
        dtm.setRowCount(0);
        Connection con = null;
        try{
            con = dbUtil.getConnection();
            ResultSet rs;
            rs = studentInfo.listByName(con,stu);
            while(rs.next()){
                Vector vec = new Vector();
                vec.add(rs.getString("stuID"));
                vec.add(rs.getString("stuName"));
                vec.add(rs.getString("stuSex"));
                vec.add(rs.getString("stuCollege"));
                vec.add(rs.getString("stuDepartment"));
                vec.add(rs.getString("stuType"));
                vec.add(rs.getString("stuPhone"));
                vec.add(rs.getString("stuRemark"));
                dtm.addRow(vec);
            }
            con.close();
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    //更新表格
    private void updateTable(Student stu){
        DefaultTableModel dtm = (DefaultTableModel)stuTable.getModel();
        dtm.setRowCount(0);
        Connection con = null;
        try{
            con = dbUtil.getConnection();
            ResultSet rs;
            if(type.equals("按学号")){
                rs = studentInfo.listByID(con,this.IDOrNameText.getText());
            }
            else{
                rs = studentInfo.listByName(con,stu);
            }
            int rsIsEmptyFlag = 0;
            while(rs.next()){
                rsIsEmptyFlag = 1;
                Vector vec = new Vector();
                vec.add(rs.getString("stuID"));
                vec.add(rs.getString("stuName"));
                vec.add(rs.getString("stuSex"));
                vec.add(rs.getString("stuCollege"));
                vec.add(rs.getString("stuDepartment"));
                vec.add(rs.getString("stuType"));
                vec.add(rs.getString("stuPhone"));
                vec.add(rs.getString("stuRemark"));
                dtm.addRow(vec);
            }
            con.close();
            if(rsIsEmptyFlag == 0){
                JOptionPane.showMessageDialog(null, "查无此人！");
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDOrNameText;
    private javax.swing.JRadioButton accordIDButton;
    private javax.swing.JRadioButton accordNameButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton modifyButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JButton searchButton1;
    private javax.swing.JTextField stuCollegeText;
    private javax.swing.JTextField stuDepartmentText;
    private javax.swing.JTextField stuIDText;
    private javax.swing.JTextField stuNameText;
    private javax.swing.JTextField stuPhoneText;
    private javax.swing.JTextField stuRemarkText;
    private javax.swing.JTable stuTable;
    private javax.swing.JScrollPane stuTableScrollPane;
    // End of variables declaration//GEN-END:variables

    //学生表格单击显示事件
    private void stuTableMousePressedAction(MouseEvent evt) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        int row = stuTable.getSelectedRow();
        this.stuIDText.setText((String)stuTable.getValueAt(row, 0));
        this.stuNameText.setText((String)stuTable.getValueAt(row, 1));
        this.stuCollegeText.setText((String)stuTable.getValueAt(row, 3));
        this.stuDepartmentText.setText((String)stuTable.getValueAt(row, 4));
        this.stuPhoneText.setText((String)stuTable.getValueAt(row, 6));
        this.stuRemarkText.setText((String)stuTable.getValueAt(row, 7));
    }

    private void modifyActionPerformed(ActionEvent evt) throws Exception {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        String stuID = this.stuIDText.getText();
        String stuCollege = this.stuCollegeText.getText();
        String stuDepartment = this.stuDepartmentText.getText();
        String stuPhone = this.stuPhoneText.getText();
        String stuRemark = this.stuRemarkText.getText();
        if(StringUtil.isEmpty(stuID)){
            JOptionPane.showMessageDialog(null, "请先选择一条学生信息！");
            return;
        }
        if(StringUtil.isEmpty(stuCollege)){
            JOptionPane.showMessageDialog(null, "学院不能为空！");
            return;
        }
        if(StringUtil.isEmpty(stuDepartment)){
            JOptionPane.showMessageDialog(null, "系不能为空！");
            return;
        }
        if(StringUtil.isEmpty(stuPhone)){
            JOptionPane.showMessageDialog(null, "手机不能为空！");
            return;
        }
        if(!StringUtil.isAllNumber(stuPhone)){
            JOptionPane.showMessageDialog(null, "请输入合法的手机号！");
            return;
        }
        if(stuPhone.length() != 11){
            JOptionPane.showMessageDialog(null, "请输入11位的手机号！");
            return;
        }
        int confirm = JOptionPane.showConfirmDialog(null, "确认修改？");
        if(confirm == 0){//确认修改
            Student stu = new Student(stuID,stuCollege,stuDepartment,stuPhone,stuRemark);
            Connection con = dbUtil.getConnection();
            int modify = studentInfo.updateInfo(con, stu);
            if(modify == 1){
                JOptionPane.showMessageDialog(null, "修改成功！");
                resetValues();
            }
            else{
                JOptionPane.showMessageDialog(null, "修改失败！");
                return;
            }
            initTable(new Student());//初始化表格
        }
    }

    private void resetValues() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        this.stuIDText.setText("");
        this.stuNameText.setText("");
        this.stuCollegeText.setText("");
        this.stuDepartmentText.setText("");
        this.stuPhoneText.setText("");
        this.stuRemarkText.setText("");
    }

    private void deleteActionPerformed(ActionEvent evt) throws Exception {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        String stuID = this.stuIDText.getText();
        if(StringUtil.isEmpty(stuID)){
            JOptionPane.showMessageDialog(null, "请先选择一条学生信息！");
            return;
        }
        int confirm = JOptionPane.showConfirmDialog(null, "确认删除？");
        if(confirm == 0){//确认删除
            Connection con = dbUtil.getConnection();
            int delete = studentInfo.deleteInfo(con, stuID);
            if(delete == 1){
                JOptionPane.showMessageDialog(null, "删除成功！");
                resetValues();
            }
            else{
                JOptionPane.showMessageDialog(null, "删除失败！");
                return;
            }
            initTable(new Student());//初始化表格
        }
    }

    private void resetSearchValues() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        this.IDOrNameText.setText("");
        this.accordIDButton.setSelected(true);
        this.accordNameButton.setSelected(false);
        type = this.accordIDButton.getText();
    }
}
