/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;
import function.AdminInfo;
import function.EquipmentInfo;
import function.StudentInfo;
import function.TeacherInfo;
import java.awt.event.ActionEvent;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Admin;
import model.Equipment;
import model.Student;
import model.Teacher;
import util.DbUtil;
import util.StringUtil;
/**
 *
 * @author ZP Chen
 */
public class ShowAdminInfo extends javax.swing.JInternalFrame {

    /**
     * Creates new form ShowBorrowInternalFrame
     */
    private String type = "按姓名";
    DbUtil dbUtil = new DbUtil();
    AdminInfo adminInfo = new AdminInfo();
    public ShowAdminInfo() {
        initComponents();
        this.initTable(new Admin());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        accordIDButton = new javax.swing.JRadioButton();
        accordNameButton = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        IDOrNameText = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        adminTableScrollPane = new javax.swing.JScrollPane();
        adminTable = new javax.swing.JTable();
        searchButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        adminIDText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        adminPhoneText = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        adminLogInPasswordText = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        deleteButton = new javax.swing.JButton();
        modifyButton = new javax.swing.JButton();
        adminRemarkText = new javax.swing.JTextField();
        adminNameText = new javax.swing.JTextField();
        adminLogInNameText = new javax.swing.JTextField();

        setClosable(true);
        setTitle("管理员信息维护");
        setToolTipText("");

        jLabel3.setFont(new java.awt.Font("华文行楷", 0, 24)); // NOI18N
        jLabel3.setText("查询类型");

        accordIDButton.setSelected(true);
        accordIDButton.setText("按姓名");
        accordIDButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accordIDButtonActionPerformed(evt);
            }
        });

        accordNameButton.setText("按编号");
        accordNameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accordNameButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("华文行楷", 0, 24)); // NOI18N
        jLabel1.setText("姓名/编号");

        IDOrNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDOrNameTextActionPerformed(evt);
            }
        });

        searchButton.setFont(new java.awt.Font("华文行楷", 0, 18)); // NOI18N
        searchButton.setText("查询");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        adminTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        adminTable.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        adminTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "编号", "姓名", "性别", "手机", "兴趣", "登录用户名", "登录密码"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        adminTable.setGridColor(new java.awt.Color(204, 204, 204));
        adminTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                adminTableMousePressed(evt);
            }
        });
        adminTableScrollPane.setViewportView(adminTable);

        searchButton1.setFont(new java.awt.Font("华文行楷", 0, 18)); // NOI18N
        searchButton1.setText("查看所有");
        searchButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButton1ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("华文行楷", 0, 24)); // NOI18N
        jLabel4.setText("编号");

        jLabel6.setFont(new java.awt.Font("华文行楷", 0, 24)); // NOI18N
        jLabel6.setText("姓名");

        adminIDText.setEditable(false);
        adminIDText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminIDTextActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("华文行楷", 0, 24)); // NOI18N
        jLabel5.setText("手机*");

        adminPhoneText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminPhoneTextActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("华文行楷", 0, 24)); // NOI18N
        jLabel7.setText("用户名");

        jLabel8.setFont(new java.awt.Font("华文行楷", 0, 24)); // NOI18N
        jLabel8.setText("密码*");

        adminLogInPasswordText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminLogInPasswordTextActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("华文行楷", 0, 24)); // NOI18N
        jLabel9.setText("兴趣");

        deleteButton.setFont(new java.awt.Font("华文行楷", 0, 18)); // NOI18N
        deleteButton.setText("删除");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        modifyButton.setFont(new java.awt.Font("华文行楷", 0, 18)); // NOI18N
        modifyButton.setText("修改");
        modifyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyButtonActionPerformed(evt);
            }
        });

        adminRemarkText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminRemarkTextActionPerformed(evt);
            }
        });

        adminNameText.setEditable(false);
        adminNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminNameTextActionPerformed(evt);
            }
        });

        adminLogInNameText.setEditable(false);
        adminLogInNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminLogInNameTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(adminIDText, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(adminLogInPasswordText, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(adminPhoneText, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(adminNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(adminLogInNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(adminRemarkText, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(modifyButton)
                .addGap(70, 70, 70)
                .addComponent(deleteButton)
                .addGap(227, 227, 227))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(adminIDText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5)
                    .addComponent(adminPhoneText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminLogInNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(adminLogInPasswordText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminRemarkText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteButton)
                    .addComponent(modifyButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(accordIDButton)
                                .addGap(18, 18, 18)
                                .addComponent(accordNameButton)
                                .addGap(18, 18, 18)
                                .addComponent(searchButton)
                                .addGap(18, 18, 18)
                                .addComponent(searchButton1))
                            .addComponent(IDOrNameText)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(adminTableScrollPane)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(accordIDButton)
                    .addComponent(accordNameButton)
                    .addComponent(searchButton)
                    .addComponent(searchButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(IDOrNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(adminTableScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                .addGap(36, 36, 36)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void accordIDButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accordIDButtonActionPerformed
        // TODO add your handling code here:
        if(!this.accordIDButton.isSelected()){
            this.accordIDButton.setSelected(true);
        }
        this.accordNameButton.setSelected(false);
        type = this.accordIDButton.getText();
    }//GEN-LAST:event_accordIDButtonActionPerformed

    private void accordNameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accordNameButtonActionPerformed
        // TODO add your handling code here:
        if(!this.accordNameButton.isSelected()){
            this.accordNameButton.setSelected(true);
        }
        this.accordIDButton.setSelected(false);
        type = this.accordNameButton.getText();
    }//GEN-LAST:event_accordNameButtonActionPerformed

    private void IDOrNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDOrNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDOrNameTextActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed

        // TODO add your handling code here:
        //根据编号或姓名查询
        Admin admin = new Admin();
        String idOrNameText = this.IDOrNameText.getText();
        if(StringUtil.isEmpty(idOrNameText)){
            JOptionPane.showMessageDialog(null,"输入不能为空！");
            return;
        }
        if(type.equals("按姓名")){
            admin.setAdminName(idOrNameText);
        }
        if(type.equals("按编号") && !StringUtil.isAllNumber(idOrNameText)){
            JOptionPane.showMessageDialog(null,"请输入正确格式的编号！");
            return;
        }
        this.updateTable(admin);
        resetSearchValues();
    }//GEN-LAST:event_searchButtonActionPerformed

    private void searchButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButton1ActionPerformed
        // TODO add your handling code here:
        this.initTable(new Admin());
    }//GEN-LAST:event_searchButton1ActionPerformed

    private void adminIDTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminIDTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminIDTextActionPerformed

    private void adminPhoneTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminPhoneTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminPhoneTextActionPerformed

    private void adminLogInPasswordTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminLogInPasswordTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminLogInPasswordTextActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        //管理员信息删除操作
        try{
            deleteActionPerformed(evt);
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void modifyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyButtonActionPerformed
        // TODO add your handling code here:
        //管理员信息修改操作
        try{
            modifyActionPerformed(evt);
        }catch(Exception e){
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_modifyButtonActionPerformed

    private void adminRemarkTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminRemarkTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminRemarkTextActionPerformed

    private void adminNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminNameTextActionPerformed

    private void adminLogInNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminLogInNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminLogInNameTextActionPerformed

    private void adminTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminTableMousePressed
        // TODO add your handling code here:
        //管理员表格单击事件
        adminTableMousePressedAction(evt);
    }//GEN-LAST:event_adminTableMousePressed

    //初始化表格
    private void initTable(Admin admin){
        DefaultTableModel dtm = (DefaultTableModel)adminTable.getModel();
        dtm.setRowCount(0);
        Connection con = null;
        try{
            con = dbUtil.getConnection();
            ResultSet rs;
            rs = adminInfo.listByName(con,admin);
            while(rs.next()){
                Vector vec = new Vector();
                vec.add(rs.getInt("adminID"));
                vec.add(rs.getString("adminName"));
                vec.add(rs.getString("adminSex"));
                vec.add(rs.getString("adminPhone"));
                vec.add(rs.getString("adminRemark"));
                vec.add(rs.getString("logInName"));
                vec.add(rs.getString("logInPassword"));
                dtm.addRow(vec);
            }
            con.close();
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    //更新表格
    private void updateTable(Admin admin){
        DefaultTableModel dtm = (DefaultTableModel)adminTable.getModel();
        dtm.setRowCount(0);
        Connection con = null;
        try{
            con = dbUtil.getConnection();
            ResultSet rs;
            if(type.equals("按编号")){
                rs = adminInfo.listByID(con,this.IDOrNameText.getText());
            }
            else{
                rs = adminInfo.listByName(con,admin);
            }
            int rsIsEmptyFlag = 0;
            while(rs.next()){
                rsIsEmptyFlag = 1;
                Vector vec = new Vector();
                vec.add(rs.getInt("adminID"));
                vec.add(rs.getString("adminName"));
                vec.add(rs.getString("adminSex"));
                vec.add(rs.getString("adminPhone"));
                vec.add(rs.getString("adminRemark"));
                vec.add(rs.getString("logInName"));
                vec.add(rs.getString("logInPassword"));
                dtm.addRow(vec);
            }
            con.close();
            if(rsIsEmptyFlag == 0){
                JOptionPane.showMessageDialog(null, "查无此人！");
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDOrNameText;
    private javax.swing.JRadioButton accordIDButton;
    private javax.swing.JRadioButton accordNameButton;
    private javax.swing.JTextField adminIDText;
    private javax.swing.JTextField adminLogInNameText;
    private javax.swing.JTextField adminLogInPasswordText;
    private javax.swing.JTextField adminNameText;
    private javax.swing.JTextField adminPhoneText;
    private javax.swing.JTextField adminRemarkText;
    private javax.swing.JTable adminTable;
    private javax.swing.JScrollPane adminTableScrollPane;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton modifyButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JButton searchButton1;
    // End of variables declaration//GEN-END:variables

    private void adminTableMousePressedAction(MouseEvent evt) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        int row = adminTable.getSelectedRow();
        this.adminIDText.setText(adminTable.getValueAt(row, 0).toString());
        this.adminNameText.setText((String)adminTable.getValueAt(row, 1));
        this.adminLogInNameText.setText((String)adminTable.getValueAt(row, 5));
        this.adminLogInPasswordText.setText((String)adminTable.getValueAt(row, 6));
        this.adminPhoneText.setText((String)adminTable.getValueAt(row, 3));
        this.adminRemarkText.setText((String)adminTable.getValueAt(row, 4));
    }

    private void modifyActionPerformed(ActionEvent evt) throws Exception {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        String adminID = this.adminIDText.getText();
        String adminPhone = this.adminPhoneText.getText();
        String logInName = this.adminLogInNameText.getText();
        String logInPassword = this.adminLogInPasswordText.getText();
        String adminRemark = this.adminRemarkText.getText();
        if(StringUtil.isEmpty(adminID)){
            JOptionPane.showMessageDialog(null, "请先选择一条管理员信息！");
            return;
        }
        if(adminID.equals("1")){
            JOptionPane.showMessageDialog(null, "超级用户禁止修改！");
            return;
        }
        if(StringUtil.isEmpty(adminPhone)){
            JOptionPane.showMessageDialog(null, "手机不能为空！");
            return;
        }
        if(StringUtil.isEmpty(logInName)){
            JOptionPane.showMessageDialog(null, "用户名不能为空！");
            return;
        }
        if(StringUtil.isEmpty(logInPassword)){
            JOptionPane.showMessageDialog(null, "密码不能为空！");
            return;
        }
        if(!StringUtil.isAllNumber(adminPhone)){
            JOptionPane.showMessageDialog(null, "请输入合法的手机号！");
            return;
        }
        if(adminPhone.length() != 11){
            JOptionPane.showMessageDialog(null, "请输入11位的手机号！");
            return;
        }
        if(logInPassword.length() < 6){
            JOptionPane.showMessageDialog(null, "密码强度过低！请输入不低于6位的密码！");
            return;
        }
        int confirm = JOptionPane.showConfirmDialog(null, "确认修改？");
        if(confirm == 0){//确认修改
            Admin admin = new Admin(adminPhone,logInName,logInPassword,adminRemark);
            Connection con = dbUtil.getConnection();
            int modify = adminInfo.updateInfo(con, admin, adminID);
            if(modify == 1){
                JOptionPane.showMessageDialog(null, "修改成功！");
                resetValues();
            }
            else{
                JOptionPane.showMessageDialog(null, "修改失败！");
                return;
            }
            initTable(new Admin());//初始化表格
        }
    }

    private void deleteActionPerformed(ActionEvent evt) throws Exception {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        String adminID = this.adminIDText.getText();
        if(StringUtil.isEmpty(adminID)){
            JOptionPane.showMessageDialog(null, "请先选择一条管理员信息！");
            return;
        }
        if(adminID.equals("1")){
            JOptionPane.showMessageDialog(null, "超级用户禁止删除！");
            return;
        }
        int confirm = JOptionPane.showConfirmDialog(null, "确认删除？");
        if(confirm == 0){//确认删除
            Connection con = dbUtil.getConnection();
            int delete = adminInfo.deleteInfo(con, adminID);
            if(delete == 1){
                JOptionPane.showMessageDialog(null, "删除成功！");
                resetValues();
            }
            else{
                JOptionPane.showMessageDialog(null, "删除失败！");
                return;
            }
            initTable(new Admin());//初始化表格
        }
    }

    private void resetValues() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        this.adminIDText.setText("");
        this.adminNameText.setText("");
        this.adminPhoneText.setText("");
        this.adminLogInNameText.setText("");
        this.adminLogInPasswordText.setText("");
        this.adminRemarkText.setText("");
    }

    private void resetSearchValues() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        this.IDOrNameText.setText("");
        this.accordIDButton.setSelected(true);
        this.accordNameButton.setSelected(false);
        type = this.accordIDButton.getText();
    }
}
