/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;
import function.BorrowInfo;
import function.EquipmentInfo;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Equipment;
import util.DbUtil;
import util.StringUtil;
/**
 *
 * @author ZP Chen
 */
public class ShowBorrowHistory extends javax.swing.JInternalFrame {

    /**
     * Creates new form ShowBorrowInternalFrame
     */
    private String type = "按学生";
    DbUtil dbUtil = new DbUtil();
    BorrowInfo borrowInfo = new BorrowInfo();
    public ShowBorrowHistory() {
        initComponents();
        this.initBorrowHistoryTable("按学生");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        stuIDButton = new javax.swing.JRadioButton();
        teaIDButton = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        stuOrTeaIDText = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        borrowHistoryTableScrollPane = new javax.swing.JScrollPane();
        borrowHistoryTable = new javax.swing.JTable();
        searchAllStudentButton = new javax.swing.JButton();
        searchAllTeacherButton = new javax.swing.JButton();

        setClosable(true);
        setTitle("借用历史查询");

        jLabel3.setFont(new java.awt.Font("华文行楷", 0, 24)); // NOI18N
        jLabel3.setText("查询类型");

        stuIDButton.setSelected(true);
        stuIDButton.setText("学生");
        stuIDButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stuIDButtonActionPerformed(evt);
            }
        });

        teaIDButton.setText("老师");
        teaIDButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teaIDButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("华文行楷", 0, 24)); // NOI18N
        jLabel1.setText("学号/教工号");

        stuOrTeaIDText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stuOrTeaIDTextActionPerformed(evt);
            }
        });

        searchButton.setFont(new java.awt.Font("华文行楷", 0, 18)); // NOI18N
        searchButton.setText("查询");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        borrowHistoryTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        borrowHistoryTable.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        borrowHistoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "编号", "学号/教工号", "姓名", "器材编号", "器材名称", "借用日期", "到期日期", "归还日期"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        borrowHistoryTable.setGridColor(new java.awt.Color(204, 204, 204));
        borrowHistoryTableScrollPane.setViewportView(borrowHistoryTable);

        searchAllStudentButton.setFont(new java.awt.Font("华文行楷", 0, 18)); // NOI18N
        searchAllStudentButton.setText("查看所有学生");
        searchAllStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchAllStudentButtonActionPerformed(evt);
            }
        });

        searchAllTeacherButton.setFont(new java.awt.Font("华文行楷", 0, 18)); // NOI18N
        searchAllTeacherButton.setText("查看所有老师");
        searchAllTeacherButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchAllTeacherButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(stuIDButton)
                                .addGap(18, 18, 18)
                                .addComponent(teaIDButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(searchButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(searchAllStudentButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(searchAllTeacherButton))
                            .addComponent(stuOrTeaIDText)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(borrowHistoryTableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 754, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(stuIDButton)
                    .addComponent(teaIDButton)
                    .addComponent(searchButton)
                    .addComponent(searchAllStudentButton)
                    .addComponent(searchAllTeacherButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(stuOrTeaIDText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(borrowHistoryTableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stuIDButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stuIDButtonActionPerformed
        // TODO add your handling code here:
        if(!this.stuIDButton.isSelected()){
            this.stuIDButton.setSelected(true);
        }
        this.teaIDButton.setSelected(false);
        type = this.stuIDButton.getText();
    }//GEN-LAST:event_stuIDButtonActionPerformed

    private void teaIDButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teaIDButtonActionPerformed
        // TODO add your handling code here:
        if(!this.teaIDButton.isSelected()){
            this.teaIDButton.setSelected(true);
        }
        this.stuIDButton.setSelected(false);
        type = this.teaIDButton.getText();
    }//GEN-LAST:event_teaIDButtonActionPerformed

    private void stuOrTeaIDTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stuOrTeaIDTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stuOrTeaIDTextActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed

        // TODO add your handling code here:
        //根据学号或教工号查询
        String stuOrTeaIDText = this.stuOrTeaIDText.getText();
        if(StringUtil.isEmpty(stuOrTeaIDText)){
            JOptionPane.showMessageDialog(null,"输入不能为空！");
            return;
        }
        if(!StringUtil.isAllNumber(stuOrTeaIDText)){
            JOptionPane.showMessageDialog(null,"请输入正确格式的号码！");
            return;
        }
        if(type.equals("按学生") && stuOrTeaIDText.length() != 14){
            JOptionPane.showMessageDialog(null,"请输入14位的学号！");
            return;
        }
        if(type.equals("按老师") && stuOrTeaIDText.length() != 11){
            JOptionPane.showMessageDialog(null,"请输入11位的教工号！");
            return;
        }
        this.updateBorrowHistoryTable(type);
        resetValues();
    }//GEN-LAST:event_searchButtonActionPerformed

    private void searchAllStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchAllStudentButtonActionPerformed
        // TODO add your handling code here:
        this.initBorrowHistoryTable("按学生");
    }//GEN-LAST:event_searchAllStudentButtonActionPerformed

    private void searchAllTeacherButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchAllTeacherButtonActionPerformed
        // TODO add your handling code here:
        this.initBorrowHistoryTable("按老师");
    }//GEN-LAST:event_searchAllTeacherButtonActionPerformed
    //初始化借用历史信息表格
    private void initBorrowHistoryTable(String type){
        DefaultTableModel dtm = (DefaultTableModel)borrowHistoryTable.getModel();
        dtm.setRowCount(0);
        Connection con = null;
        try{
            con = dbUtil.getConnection();
            ResultSet rs;
            if(type.equals("按学生")){
                rs = borrowInfo.listAllStudentBorrowHistory(con);
                while(rs.next()){
                    Vector vec = new Vector();
                    vec.add(rs.getInt("ID"));
                    vec.add(rs.getString("stuID"));
                    vec.add(rs.getString("stuName"));
                    vec.add(rs.getString("equipID"));
                    vec.add(rs.getString("equipName"));
                    vec.add(rs.getString("borrowDate").substring(0,10));
                    vec.add(rs.getString("expireDate").substring(0,10));
                    String returnDate = rs.getString("returnDate");
                    if(StringUtil.isNotEmpty(returnDate)){
                        returnDate = returnDate.substring(0,10);
                    }
                    vec.add(returnDate);
                    dtm.addRow(vec);
                }
                con.close();
            }
            else{
                rs = borrowInfo.listAllTeacherBorrowHistory(con);
                while(rs.next()){
                    Vector vec = new Vector();
                    vec.add(rs.getInt("ID"));
                    vec.add(rs.getString("teaID"));
                    vec.add(rs.getString("teaName"));
                    vec.add(rs.getString("equipID"));
                    vec.add(rs.getString("equipName"));
                    vec.add(rs.getString("borrowDate").substring(0,10));
                    vec.add(rs.getString("expireDate").substring(0,10));
                    String returnDate = rs.getString("returnDate");
                    if(StringUtil.isNotEmpty(returnDate)){
                        returnDate = returnDate.substring(0,10);
                    }
                    vec.add(returnDate);
                    dtm.addRow(vec);
                }
                con.close();
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    //更新借用历史信息表格
    private void updateBorrowHistoryTable(String type){
        DefaultTableModel dtm = (DefaultTableModel)borrowHistoryTable.getModel();
        dtm.setRowCount(0);
        Connection con = null;
        try{
            con = dbUtil.getConnection();
            ResultSet rs;
            if(type.equals("按学生")){
                rs = borrowInfo.listAllStudentBorrowHistoryByID(con,this.stuOrTeaIDText.getText());
                int rsIsEmptyFlag = 0;
                while(rs.next()){
                    rsIsEmptyFlag = 1;
                    Vector vec = new Vector();
                    vec.add(rs.getString("stuID"));
                    vec.add(rs.getString("stuName"));
                    vec.add(rs.getString("equipID"));
                    vec.add(rs.getString("equipName"));
                    vec.add(rs.getString("borrowDate").substring(0,10));
                    vec.add(rs.getString("expireDate").substring(0,10));
                    String returnDate = rs.getString("returnDate");
                    if(StringUtil.isNotEmpty(returnDate)){
                        returnDate = returnDate.substring(0,10);
                    }
                    vec.add(returnDate);
                    dtm.addRow(vec);
                }
                con.close();
                if(rsIsEmptyFlag == 0){
                    JOptionPane.showMessageDialog(null, "查无此信息！");
                }
            }
            else{
                rs = borrowInfo.listAllTeacherBorrowHistoryByID(con,this.stuOrTeaIDText.getText());
                int rsIsEmptyFlag = 0;
                while(rs.next()){
                    rsIsEmptyFlag = 1;
                    Vector vec = new Vector();
                    vec.add(rs.getString("teaID"));
                    vec.add(rs.getString("teaName"));
                    vec.add(rs.getString("equipID"));
                    vec.add(rs.getString("equipName"));
                    vec.add(rs.getString("borrowDate").substring(0,10));
                    vec.add(rs.getString("expireDate").substring(0,10));
                    String returnDate = rs.getString("returnDate");
                    if(StringUtil.isNotEmpty(returnDate)){
                        returnDate = returnDate.substring(0,10);
                    }
                    vec.add(returnDate);
                    dtm.addRow(vec);
                }
                con.close();
                if(rsIsEmptyFlag == 0){
                    JOptionPane.showMessageDialog(null, "查无此信息！");
                }
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable borrowHistoryTable;
    private javax.swing.JScrollPane borrowHistoryTableScrollPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton searchAllStudentButton;
    private javax.swing.JButton searchAllTeacherButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JRadioButton stuIDButton;
    private javax.swing.JTextField stuOrTeaIDText;
    private javax.swing.JRadioButton teaIDButton;
    // End of variables declaration//GEN-END:variables

    private void resetValues() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        this.stuOrTeaIDText.setText("");
        this.stuIDButton.setSelected(true);
        this.teaIDButton.setSelected(false);
        type = this.stuIDButton.getText();
    }
}
