/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;
import function.EquipmentInfo;
import function.StudentInfo;
import function.TeacherInfo;
import java.awt.event.ActionEvent;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Equipment;
import model.Student;
import model.Teacher;
import util.DbUtil;
import util.StringUtil;
/**
 *
 * @author ZP Chen
 */
public class ShowTeacherInfo extends javax.swing.JInternalFrame {

    /**
     * Creates new form ShowBorrowInternalFrame
     */
    private String type = "按姓名";
    DbUtil dbUtil = new DbUtil();
    TeacherInfo teacherInfo = new TeacherInfo();
    public ShowTeacherInfo() {
        initComponents();
        this.initTable(new Teacher());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        accordIDButton = new javax.swing.JRadioButton();
        accordNameButton = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        IDOrNameText = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        teaTableScrollPane = new javax.swing.JScrollPane();
        teaTable = new javax.swing.JTable();
        searchButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        teaIDText = new javax.swing.JTextField();
        teaNameText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        teaCollegeText = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        teaDepartmentText = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        teaTypeText = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        teaPhoneText = new javax.swing.JTextField();
        deleteButton = new javax.swing.JButton();
        modifyButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        teaRemarkText = new javax.swing.JTextField();

        setClosable(true);
        setTitle("老师信息维护");
        setToolTipText("");

        jLabel3.setFont(new java.awt.Font("华文行楷", 0, 24)); // NOI18N
        jLabel3.setText("查询类型");

        accordIDButton.setSelected(true);
        accordIDButton.setText("按姓名");
        accordIDButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accordIDButtonActionPerformed(evt);
            }
        });

        accordNameButton.setText("按教工号");
        accordNameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accordNameButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("华文行楷", 0, 24)); // NOI18N
        jLabel1.setText("姓名/教工号");

        IDOrNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDOrNameTextActionPerformed(evt);
            }
        });

        searchButton.setFont(new java.awt.Font("华文行楷", 0, 18)); // NOI18N
        searchButton.setText("查询");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        teaTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        teaTable.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        teaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "教工号", "姓名", "性别", "学院", "系", "类型", "手机", "兴趣"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        teaTable.setGridColor(new java.awt.Color(204, 204, 204));
        teaTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                teaTableMousePressed(evt);
            }
        });
        teaTableScrollPane.setViewportView(teaTable);

        searchButton1.setFont(new java.awt.Font("华文行楷", 0, 18)); // NOI18N
        searchButton1.setText("查看所有");
        searchButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButton1ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("华文行楷", 0, 24)); // NOI18N
        jLabel4.setText("工号");

        jLabel6.setFont(new java.awt.Font("华文行楷", 0, 24)); // NOI18N
        jLabel6.setText("姓名");

        teaIDText.setEditable(false);
        teaIDText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teaIDTextActionPerformed(evt);
            }
        });

        teaNameText.setEditable(false);
        teaNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teaNameTextActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("华文行楷", 0, 24)); // NOI18N
        jLabel5.setText("学院*");

        teaCollegeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teaCollegeTextActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("华文行楷", 0, 24)); // NOI18N
        jLabel7.setText("系*");

        teaDepartmentText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teaDepartmentTextActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("华文行楷", 0, 24)); // NOI18N
        jLabel8.setText("类型*");

        teaTypeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teaTypeTextActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("华文行楷", 0, 24)); // NOI18N
        jLabel9.setText("手机*");

        teaPhoneText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teaPhoneTextActionPerformed(evt);
            }
        });

        deleteButton.setFont(new java.awt.Font("华文行楷", 0, 18)); // NOI18N
        deleteButton.setText("删除");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        modifyButton.setFont(new java.awt.Font("华文行楷", 0, 18)); // NOI18N
        modifyButton.setText("修改");
        modifyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyButtonActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("华文行楷", 0, 24)); // NOI18N
        jLabel10.setText("兴趣");

        teaRemarkText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teaRemarkTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(271, 271, 271)
                .addComponent(modifyButton)
                .addGap(70, 70, 70)
                .addComponent(deleteButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(teaRemarkText))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(teaIDText, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(teaCollegeText, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(teaTypeText, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(teaNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(teaDepartmentText, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(teaPhoneText, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel6)
                    .addComponent(teaNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(teaIDText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel7)
                    .addComponent(teaDepartmentText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(teaCollegeText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel9)
                    .addComponent(teaPhoneText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(teaTypeText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teaRemarkText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteButton)
                    .addComponent(modifyButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(accordIDButton)
                                .addGap(18, 18, 18)
                                .addComponent(accordNameButton)
                                .addGap(18, 18, 18)
                                .addComponent(searchButton)
                                .addGap(18, 18, 18)
                                .addComponent(searchButton1))
                            .addComponent(IDOrNameText)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(teaTableScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(accordIDButton)
                    .addComponent(accordNameButton)
                    .addComponent(searchButton)
                    .addComponent(searchButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(IDOrNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(teaTableScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void accordIDButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accordIDButtonActionPerformed
        // TODO add your handling code here:
        if(!this.accordIDButton.isSelected()){
            this.accordIDButton.setSelected(true);
        }
        this.accordNameButton.setSelected(false);
        type = this.accordIDButton.getText();
    }//GEN-LAST:event_accordIDButtonActionPerformed

    private void accordNameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accordNameButtonActionPerformed
        // TODO add your handling code here:
        if(!this.accordNameButton.isSelected()){
            this.accordNameButton.setSelected(true);
        }
        this.accordIDButton.setSelected(false);
        type = this.accordNameButton.getText();
    }//GEN-LAST:event_accordNameButtonActionPerformed

    private void IDOrNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDOrNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDOrNameTextActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed

        // TODO add your handling code here:
        //根据教工号或姓名查询
        Teacher tea = new Teacher();
        String idOrNameText = this.IDOrNameText.getText();
        if(StringUtil.isEmpty(idOrNameText)){
            JOptionPane.showMessageDialog(null,"输入不能为空！");
            return;
        }
        if(type.equals("按姓名")){
            tea.setTeaName(idOrNameText);
        }
        if(type.equals("按教工号") && !StringUtil.isAllNumber(idOrNameText)){
            JOptionPane.showMessageDialog(null,"请输入正确格式的教工号！");
            return;
        }
        if(type.equals("按教工号") && idOrNameText.length() != 11){
            JOptionPane.showMessageDialog(null,"请输入11位的教工号！");
            return;
        }
        this.updateTable(tea);
        resetSearchValues();
    }//GEN-LAST:event_searchButtonActionPerformed

    private void searchButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButton1ActionPerformed
        // TODO add your handling code here:
        this.initTable(new Teacher());
    }//GEN-LAST:event_searchButton1ActionPerformed

    private void teaIDTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teaIDTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teaIDTextActionPerformed

    private void teaNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teaNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teaNameTextActionPerformed

    private void teaCollegeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teaCollegeTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teaCollegeTextActionPerformed

    private void teaDepartmentTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teaDepartmentTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teaDepartmentTextActionPerformed

    private void teaTypeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teaTypeTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teaTypeTextActionPerformed

    private void teaPhoneTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teaPhoneTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teaPhoneTextActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        try{
            deleteActionPerformed(evt);
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void modifyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyButtonActionPerformed
        // TODO add your handling code here:
        try{
            modifyActionPerformed(evt);
        }catch(Exception e){
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_modifyButtonActionPerformed

    private void teaRemarkTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teaRemarkTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teaRemarkTextActionPerformed

    private void teaTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teaTableMousePressed
        // TODO add your handling code here:
        //教师表格单击事件
        teaTableMousePressedAction(evt);
    }//GEN-LAST:event_teaTableMousePressed

    //初始化表格
    private void initTable(Teacher tea){
        DefaultTableModel dtm = (DefaultTableModel)teaTable.getModel();
        dtm.setRowCount(0);
        Connection con = null;
        try{
            con = dbUtil.getConnection();
            ResultSet rs;
            rs = teacherInfo.listByName(con,tea);
            while(rs.next()){
                Vector vec = new Vector();
                vec.add(rs.getString("teaID"));
                vec.add(rs.getString("teaName"));
                vec.add(rs.getString("teaSex"));
                vec.add(rs.getString("teaCollege"));
                vec.add(rs.getString("teaDepartment"));
                vec.add(rs.getString("teaType"));
                vec.add(rs.getString("teaPhone"));
                vec.add(rs.getString("teaRemark"));
                dtm.addRow(vec);
            }
            con.close();
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    //更新表格
    private void updateTable(Teacher tea){
        DefaultTableModel dtm = (DefaultTableModel)teaTable.getModel();
        dtm.setRowCount(0);
        Connection con = null;
        try{
            con = dbUtil.getConnection();
            ResultSet rs;
            if(type.equals("按教工号")){
                rs = teacherInfo.listByID(con,this.IDOrNameText.getText());
            }
            else{
                rs = teacherInfo.listByName(con,tea);
            }
            int rsIsEmptyFlag = 0;
            while(rs.next()){
                rsIsEmptyFlag = 1;
                Vector vec = new Vector();
                vec.add(rs.getString("teaID"));
                vec.add(rs.getString("teaName"));
                vec.add(rs.getString("teaSex"));
                vec.add(rs.getString("teaCollege"));
                vec.add(rs.getString("teaDepartment"));
                vec.add(rs.getString("teaType"));
                vec.add(rs.getString("teaPhone"));
                vec.add(rs.getString("teaRemark"));
                dtm.addRow(vec);
            }
            con.close();
            if(rsIsEmptyFlag == 0){
                JOptionPane.showMessageDialog(null, "查无此人！");
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDOrNameText;
    private javax.swing.JRadioButton accordIDButton;
    private javax.swing.JRadioButton accordNameButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton modifyButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JButton searchButton1;
    private javax.swing.JTextField teaCollegeText;
    private javax.swing.JTextField teaDepartmentText;
    private javax.swing.JTextField teaIDText;
    private javax.swing.JTextField teaNameText;
    private javax.swing.JTextField teaPhoneText;
    private javax.swing.JTextField teaRemarkText;
    private javax.swing.JTable teaTable;
    private javax.swing.JScrollPane teaTableScrollPane;
    private javax.swing.JTextField teaTypeText;
    // End of variables declaration//GEN-END:variables

    private void teaTableMousePressedAction(MouseEvent evt) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        int row = teaTable.getSelectedRow();
        this.teaIDText.setText((String)teaTable.getValueAt(row, 0));
        this.teaNameText.setText((String)teaTable.getValueAt(row, 1));
        this.teaCollegeText.setText((String)teaTable.getValueAt(row, 3));
        this.teaDepartmentText.setText((String)teaTable.getValueAt(row, 4));
        this.teaTypeText.setText((String)teaTable.getValueAt(row, 5));
        this.teaPhoneText.setText((String)teaTable.getValueAt(row, 6));
        this.teaRemarkText.setText((String)teaTable.getValueAt(row, 7));
    }

    private void modifyActionPerformed(ActionEvent evt) throws Exception {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        String teaID = this.teaIDText.getText();
        String teaCollege = this.teaCollegeText.getText();
        String teaDepartment = this.teaDepartmentText.getText();
        String teaType = this.teaTypeText.getText();
        String teaPhone = this.teaPhoneText.getText();
        String teaRemark = this.teaRemarkText.getText();
        if(StringUtil.isEmpty(teaID)){
            JOptionPane.showMessageDialog(null, "请先选择一条老师信息！");
            return;
        }
        if(StringUtil.isEmpty(teaCollege)){
            JOptionPane.showMessageDialog(null, "学院不能为空！");
            return;
        }
        if(StringUtil.isEmpty(teaDepartment)){
            JOptionPane.showMessageDialog(null, "系不能为空！");
            return;
        }
        if(StringUtil.isEmpty(teaType)){
            JOptionPane.showMessageDialog(null, "类型不能为空！");
            return;
        }
        if(StringUtil.isEmpty(teaPhone)){
            JOptionPane.showMessageDialog(null, "手机不能为空！");
            return;
        }
        if(!StringUtil.isAllNumber(teaPhone)){
            JOptionPane.showMessageDialog(null, "请输入合法的手机号！");
            return;
        }
        if(teaPhone.length() != 11){
            JOptionPane.showMessageDialog(null, "请输入11位的手机号！");
            return;
        }
        int confirm = JOptionPane.showConfirmDialog(null, "确认修改？");
        if(confirm == 0){//确认修改
            Teacher tea = new Teacher(teaID,teaCollege,teaDepartment,teaType,teaPhone,teaRemark);
            Connection con = dbUtil.getConnection();
            int modify = teacherInfo.updateInfo(con, tea);
            if(modify == 1){
                JOptionPane.showMessageDialog(null, "修改成功！");
                resetValues();
            }
            else{
                JOptionPane.showMessageDialog(null, "修改失败！");
                return;
            }
            initTable(new Teacher());//初始化表格
        }
    }

    private void deleteActionPerformed(ActionEvent evt) throws Exception {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        String teaID = this.teaIDText.getText();
        if(StringUtil.isEmpty(teaID)){
            JOptionPane.showMessageDialog(null, "请先选择一条老师信息！");
            return;
        }
        int confirm = JOptionPane.showConfirmDialog(null, "确认删除？");
        if(confirm == 0){//确认删除
            Connection con = dbUtil.getConnection();
            int delete = teacherInfo.deleteInfo(con, teaID);
            if(delete == 1){
                JOptionPane.showMessageDialog(null, "删除成功！");
                resetValues();
            }
            else{
                JOptionPane.showMessageDialog(null, "删除失败！");
                return;
            }
            initTable(new Teacher());//初始化表格
        }
    }

    private void resetValues() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        this.teaIDText.setText("");
        this.teaNameText.setText("");
        this.teaCollegeText.setText("");
        this.teaDepartmentText.setText("");
        this.teaTypeText.setText("");
        this.teaPhoneText.setText("");
        this.teaRemarkText.setText("");
    }

    private void resetSearchValues() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        this.IDOrNameText.setText("");
        this.accordIDButton.setSelected(true);
        this.accordNameButton.setSelected(false);
        type = this.accordIDButton.getText();
    }
}
