/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import function.StudentInfo;
import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Student;
import util.DbUtil;
import util.StringUtil;

/**
 *
 * @author ZP Chen
 */
public class StuInfoAdd extends javax.swing.JInternalFrame {

    /**
     * Creates new form StuInfoMaintainInternalFrame
     */
    String stuSex;//学生性别
    String stuType;//学生类型本科/硕士/博士
    DbUtil dbUtil = new DbUtil();
    StudentInfo studentInfo = new StudentInfo();
    public StuInfoAdd() {
        initComponents();
        stuSex = this.stuManRadioButton.getText();
        stuType = this.stuBachelorRadioButton.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        stuInfoAddButton = new javax.swing.JButton();
        stuInfoResetButton = new javax.swing.JButton();
        stuManRadioButton = new javax.swing.JRadioButton();
        stuWomanRadioButton = new javax.swing.JRadioButton();
        stuBachelorRadioButton = new javax.swing.JRadioButton();
        stuMasterRadioButton = new javax.swing.JRadioButton();
        stuDoctorRadioButton = new javax.swing.JRadioButton();
        stuIDText = new javax.swing.JTextField();
        stuNameText = new javax.swing.JTextField();
        stuDepartmentText = new javax.swing.JTextField();
        stuCollegeText = new javax.swing.JTextField();
        stuInterestText = new javax.swing.JTextField();
        stuPhoneText = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("jRadioButtonMenuItem2");

        setClosable(true);
        setTitle("学生信息添加");

        jLabel1.setFont(new java.awt.Font("华文行楷", 0, 24)); // NOI18N
        jLabel1.setText("学号*");

        jLabel2.setFont(new java.awt.Font("华文行楷", 0, 24)); // NOI18N
        jLabel2.setText("姓名*");

        jLabel3.setFont(new java.awt.Font("华文行楷", 0, 24)); // NOI18N
        jLabel3.setText("性别*");

        jLabel4.setFont(new java.awt.Font("华文行楷", 0, 24)); // NOI18N
        jLabel4.setText("学院*");

        jLabel5.setFont(new java.awt.Font("华文行楷", 0, 24)); // NOI18N
        jLabel5.setText("系*");

        jLabel6.setFont(new java.awt.Font("华文行楷", 0, 24)); // NOI18N
        jLabel6.setText("类别*");

        jLabel7.setFont(new java.awt.Font("华文行楷", 0, 24)); // NOI18N
        jLabel7.setText("手机*");

        jLabel8.setFont(new java.awt.Font("华文行楷", 0, 24)); // NOI18N
        jLabel8.setText("兴趣");

        jLabel9.setBackground(new java.awt.Color(255, 0, 0));
        jLabel9.setFont(new java.awt.Font("华文行楷", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("填写要求：1、除兴趣一栏可选外其余均为必填！");

        stuInfoAddButton.setFont(new java.awt.Font("华文行楷", 0, 18)); // NOI18N
        stuInfoAddButton.setText("添加");
        stuInfoAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stuInfoAddButtonActionPerformed(evt);
            }
        });

        stuInfoResetButton.setFont(new java.awt.Font("华文行楷", 0, 18)); // NOI18N
        stuInfoResetButton.setText("重置");
        stuInfoResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stuInfoResetButtonActionPerformed(evt);
            }
        });

        stuManRadioButton.setSelected(true);
        stuManRadioButton.setText("男");
        stuManRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stuManRadioButtonActionPerformed(evt);
            }
        });

        stuWomanRadioButton.setText("女");
        stuWomanRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stuWomanRadioButtonActionPerformed(evt);
            }
        });

        stuBachelorRadioButton.setSelected(true);
        stuBachelorRadioButton.setText("本科生");
        stuBachelorRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stuBachelorRadioButtonActionPerformed(evt);
            }
        });

        stuMasterRadioButton.setText("研究生");
        stuMasterRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stuMasterRadioButtonActionPerformed(evt);
            }
        });

        stuDoctorRadioButton.setText("博士生");
        stuDoctorRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stuDoctorRadioButtonActionPerformed(evt);
            }
        });

        stuIDText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stuIDTextActionPerformed(evt);
            }
        });

        stuNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stuNameTextActionPerformed(evt);
            }
        });

        stuDepartmentText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stuDepartmentTextActionPerformed(evt);
            }
        });

        stuCollegeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stuCollegeTextActionPerformed(evt);
            }
        });

        stuInterestText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stuInterestTextActionPerformed(evt);
            }
        });

        stuPhoneText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stuPhoneTextActionPerformed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/student.png"))); // NOI18N

        jLabel10.setBackground(new java.awt.Color(255, 0, 0));
        jLabel10.setFont(new java.awt.Font("华文行楷", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("3、手机号为11位纯数字，如13358878188");

        jLabel12.setBackground(new java.awt.Color(255, 0, 0));
        jLabel12.setFont(new java.awt.Font("华文行楷", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setText("2、学号为14位纯数字，如34520172201888");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel8))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stuIDText, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stuNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stuCollegeText, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stuDepartmentText, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stuPhoneText, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(stuManRadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(stuWomanRadioButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(stuBachelorRadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(stuMasterRadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(stuDoctorRadioButton))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(stuInfoAddButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(stuInfoResetButton))
                                .addComponent(stuInterestText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel12))))))
                .addGap(60, 60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stuIDText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(stuNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(stuManRadioButton)
                            .addComponent(stuWomanRadioButton))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(stuCollegeText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(stuDepartmentText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(stuBachelorRadioButton)
                            .addComponent(stuMasterRadioButton)
                            .addComponent(stuDoctorRadioButton)))
                    .addComponent(jLabel11))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stuPhoneText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stuInterestText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stuInfoAddButton)
                    .addComponent(stuInfoResetButton))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stuInfoAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stuInfoAddButtonActionPerformed
       
            // TODO add your handling code here:
            //添加新学生信息
        try{
            stuInfoAddActionPerformed(evt);
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_stuInfoAddButtonActionPerformed

    private void stuManRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stuManRadioButtonActionPerformed
        // TODO add your handling code here:
        if(!this.stuManRadioButton.isSelected()){
            this.stuManRadioButton.setSelected(true);
        }
        this.stuWomanRadioButton.setSelected(false);
        stuSex = this.stuManRadioButton.getText();
        //System.out.println(stuSex);             
    }//GEN-LAST:event_stuManRadioButtonActionPerformed

    private void stuIDTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stuIDTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stuIDTextActionPerformed

    private void stuNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stuNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stuNameTextActionPerformed

    private void stuDepartmentTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stuDepartmentTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stuDepartmentTextActionPerformed

    private void stuCollegeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stuCollegeTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stuCollegeTextActionPerformed

    private void stuInterestTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stuInterestTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stuInterestTextActionPerformed

    private void stuPhoneTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stuPhoneTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stuPhoneTextActionPerformed

    private void stuInfoResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stuInfoResetButtonActionPerformed
        // TODO add your handling code here:
        stuInfoResetActionPerformed(evt);//学生信息全部重置
    }//GEN-LAST:event_stuInfoResetButtonActionPerformed

    private void stuWomanRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stuWomanRadioButtonActionPerformed
        // TODO add your handling code here:
        if(!this.stuWomanRadioButton.isSelected()){
            this.stuWomanRadioButton.setSelected(true);
        }
        this.stuManRadioButton.setSelected(false);
        stuSex = this.stuWomanRadioButton.getText();
        //System.out.println(stuSex);
    }//GEN-LAST:event_stuWomanRadioButtonActionPerformed

    private void stuBachelorRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stuBachelorRadioButtonActionPerformed
        // TODO add your handling code here:
        if(!this.stuBachelorRadioButton.isSelected()){
            this.stuBachelorRadioButton.setSelected(true);
        }
        this.stuMasterRadioButton.setSelected(false);
        this.stuDoctorRadioButton.setSelected(false);
        stuType = this.stuBachelorRadioButton.getText();
        System.out.println(stuType);
    }//GEN-LAST:event_stuBachelorRadioButtonActionPerformed

    private void stuMasterRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stuMasterRadioButtonActionPerformed
        // TODO add your handling code here:
        if(!this.stuMasterRadioButton.isSelected()){
            this.stuMasterRadioButton.setSelected(true);
        }
        this.stuBachelorRadioButton.setSelected(false);
        this.stuDoctorRadioButton.setSelected(false);
        stuType = this.stuMasterRadioButton.getText();
        System.out.println(stuType);
    }//GEN-LAST:event_stuMasterRadioButtonActionPerformed

    private void stuDoctorRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stuDoctorRadioButtonActionPerformed
        // TODO add your handling code here:
        if(!this.stuDoctorRadioButton.isSelected()){
            this.stuDoctorRadioButton.setSelected(true);
        }
        this.stuBachelorRadioButton.setSelected(false);
        this.stuMasterRadioButton.setSelected(false);
        stuType = this.stuDoctorRadioButton.getText();
        System.out.println(stuType);
    }//GEN-LAST:event_stuDoctorRadioButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JRadioButton stuBachelorRadioButton;
    private javax.swing.JTextField stuCollegeText;
    private javax.swing.JTextField stuDepartmentText;
    private javax.swing.JRadioButton stuDoctorRadioButton;
    private javax.swing.JTextField stuIDText;
    private javax.swing.JButton stuInfoAddButton;
    private javax.swing.JButton stuInfoResetButton;
    private javax.swing.JTextField stuInterestText;
    private javax.swing.JRadioButton stuManRadioButton;
    private javax.swing.JRadioButton stuMasterRadioButton;
    private javax.swing.JTextField stuNameText;
    private javax.swing.JTextField stuPhoneText;
    private javax.swing.JRadioButton stuWomanRadioButton;
    // End of variables declaration//GEN-END:variables

    private void stuInfoResetActionPerformed(ActionEvent evt) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        resetStuInfo();//重置学生信息方法
    }

    private void resetStuInfo() {//重置学生信息方法
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        this.stuIDText.setText("");
        this.stuNameText.setText("");
        this.stuCollegeText.setText("");
        this.stuDepartmentText.setText("");
        this.stuPhoneText.setText("");
        this.stuInterestText.setText("");
        this.stuManRadioButton.setSelected(true);
        this.stuWomanRadioButton.setSelected(false);
        stuSex = this.stuManRadioButton.getText();
        this.stuBachelorRadioButton.setSelected(true);
        this.stuMasterRadioButton.setSelected(false);
        this.stuDoctorRadioButton.setSelected(false);
        stuType = this.stuBachelorRadioButton.getText();
    }
    
    private void stuInfoAddActionPerformed(ActionEvent evt) throws SQLException, Exception {//添加新学生信息
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        String stuID = this.stuIDText.getText();
        String stuName = this.stuNameText.getText();
        String stuCollege = this.stuCollegeText.getText();
        String stuDepartment = this.stuDepartmentText.getText();
        String stuPhone = this.stuPhoneText.getText();
        String stuRemark = this.stuInterestText.getText();
        if(StringUtil.isEmpty(stuID)){
            JOptionPane.showMessageDialog(null,"学号不能为空！");
            return;
        }
        if(StringUtil.isEmpty(stuName)){
            JOptionPane.showMessageDialog(null,"姓名不能为空！");
            return;
        }
        if(StringUtil.isEmpty(stuCollege)){
            JOptionPane.showMessageDialog(null,"学院不能为空！");
            return;
        }
        if(StringUtil.isEmpty(stuDepartment)){
            JOptionPane.showMessageDialog(null,"系不能为空！");
            return;
        }
        if(StringUtil.isEmpty(stuPhone)){
            JOptionPane.showMessageDialog(null,"手机不能为空！");
            return;
        }
        if(stuID.length() != 14){
            JOptionPane.showMessageDialog(null,"学号位数不为14位！");
            return;
        } 
        if(!StringUtil.isAllNumber(stuID)){
            JOptionPane.showMessageDialog(null,"学号不为纯数字！");
            return;
        }
        if(stuPhone.length() != 11){
            JOptionPane.showMessageDialog(null,"手机号位数不为11位！");
            return;
        } 
        if(!StringUtil.isAllNumber(stuPhone)){
            JOptionPane.showMessageDialog(null,"手机号不为纯数字！");
            return;
        } 
        Connection con = null;
        con = dbUtil.getConnection();
        if(studentInfo.checkExist(con, stuID)){
            JOptionPane.showMessageDialog(null,"当前学号已存在，请勿重复添加！");
            return;
        }
        Student student = new Student(stuID,stuName,stuSex,stuCollege,stuDepartment,stuType,stuPhone,stuRemark);
        try{
            con = dbUtil.getConnection();
            int result = studentInfo.studentInfoAdd(con,student);
            if(result == 1){
                JOptionPane.showMessageDialog(null,"学生添加成功！");
                resetStuInfo();//重置学生信息所有栏
            }
            else{
                JOptionPane.showMessageDialog(null,"学生添加失败！");
            }
        }catch (Exception e)
        {
            e.printStackTrace();
        }
    }
}
