/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import function.TeacherInfo;
import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import model.Teacher;
import util.DbUtil;
import util.StringUtil;

/**
 *
 * @author ZP Chen
 */
public class TeaInfoAdd extends javax.swing.JInternalFrame {

    /**
     * Creates new form StuInfoMaintainInternalFrame
     */
    String teaSex;//老师性别
    String teaType;//老师类型本科/硕士/博士
    DbUtil dbUtil = new DbUtil();
    TeacherInfo teacherInfo = new TeacherInfo();
    public TeaInfoAdd() {
        initComponents();
        teaSex = this.teaManRadioButton.getText();
        teaType = this.teaRadioButton1.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        teaInfoAddButton = new javax.swing.JButton();
        teaInfoResetButton = new javax.swing.JButton();
        teaManRadioButton = new javax.swing.JRadioButton();
        teaWomanRadioButton = new javax.swing.JRadioButton();
        teaRadioButton1 = new javax.swing.JRadioButton();
        teaRadioButton2 = new javax.swing.JRadioButton();
        teaRadioButton3 = new javax.swing.JRadioButton();
        teaIDText = new javax.swing.JTextField();
        teaNameText = new javax.swing.JTextField();
        teaDepartmentText = new javax.swing.JTextField();
        teaCollegeText = new javax.swing.JTextField();
        teaInterestText = new javax.swing.JTextField();
        teaPhoneText = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        teaRadioButton4 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("jRadioButtonMenuItem2");

        setClosable(true);
        setTitle("老师信息添加");

        jLabel1.setFont(new java.awt.Font("华文行楷", 0, 24)); // NOI18N
        jLabel1.setText("教工号*");

        jLabel2.setFont(new java.awt.Font("华文行楷", 0, 24)); // NOI18N
        jLabel2.setText("姓名*");

        jLabel3.setFont(new java.awt.Font("华文行楷", 0, 24)); // NOI18N
        jLabel3.setText("性别*");

        jLabel4.setFont(new java.awt.Font("华文行楷", 0, 24)); // NOI18N
        jLabel4.setText("学院*");

        jLabel5.setFont(new java.awt.Font("华文行楷", 0, 24)); // NOI18N
        jLabel5.setText("系*");

        jLabel6.setFont(new java.awt.Font("华文行楷", 0, 24)); // NOI18N
        jLabel6.setText("类别*");

        jLabel7.setFont(new java.awt.Font("华文行楷", 0, 24)); // NOI18N
        jLabel7.setText("手机*");

        jLabel8.setFont(new java.awt.Font("华文行楷", 0, 24)); // NOI18N
        jLabel8.setText("兴趣");

        jLabel9.setBackground(new java.awt.Color(255, 0, 0));
        jLabel9.setFont(new java.awt.Font("华文行楷", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("填写要求：1、除兴趣一栏可选外其余均为必填！");

        teaInfoAddButton.setFont(new java.awt.Font("华文行楷", 0, 18)); // NOI18N
        teaInfoAddButton.setText("添加");
        teaInfoAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teaInfoAddButtonActionPerformed(evt);
            }
        });

        teaInfoResetButton.setFont(new java.awt.Font("华文行楷", 0, 18)); // NOI18N
        teaInfoResetButton.setText("重置");
        teaInfoResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teaInfoResetButtonActionPerformed(evt);
            }
        });

        teaManRadioButton.setSelected(true);
        teaManRadioButton.setText("男");
        teaManRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teaManRadioButtonActionPerformed(evt);
            }
        });

        teaWomanRadioButton.setText("女");
        teaWomanRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teaWomanRadioButtonActionPerformed(evt);
            }
        });

        teaRadioButton1.setSelected(true);
        teaRadioButton1.setText("助理教授");
        teaRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teaRadioButton1ActionPerformed(evt);
            }
        });

        teaRadioButton2.setText("副教授");
        teaRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teaRadioButton2ActionPerformed(evt);
            }
        });

        teaRadioButton3.setText("教授");
        teaRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teaRadioButton3ActionPerformed(evt);
            }
        });

        teaIDText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teaIDTextActionPerformed(evt);
            }
        });

        teaNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teaNameTextActionPerformed(evt);
            }
        });

        teaDepartmentText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teaDepartmentTextActionPerformed(evt);
            }
        });

        teaCollegeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teaCollegeTextActionPerformed(evt);
            }
        });

        teaInterestText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teaInterestTextActionPerformed(evt);
            }
        });

        teaPhoneText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teaPhoneTextActionPerformed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/teacher.png"))); // NOI18N

        teaRadioButton4.setText("其他");
        teaRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teaRadioButton4ActionPerformed(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(255, 0, 0));
        jLabel10.setFont(new java.awt.Font("华文行楷", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("2、教工号为11位纯数字，如52282168868");

        jLabel12.setBackground(new java.awt.Color(255, 0, 0));
        jLabel12.setFont(new java.awt.Font("华文行楷", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setText("3、手机号为11位纯数字，如13358878188");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel8))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(teaIDText, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(teaNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(teaCollegeText, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(teaDepartmentText, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(teaPhoneText, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(teaManRadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(teaWomanRadioButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(teaRadioButton1)
                                .addGap(18, 18, 18)
                                .addComponent(teaRadioButton2)
                                .addGap(18, 18, 18)
                                .addComponent(teaRadioButton3)
                                .addGap(18, 18, 18)
                                .addComponent(teaRadioButton4))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(teaInfoAddButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(teaInfoResetButton))
                                .addComponent(teaInterestText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel12)
                                .addComponent(jLabel9))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addComponent(jLabel10)))))
                .addGap(60, 60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teaIDText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(teaNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(teaManRadioButton)
                            .addComponent(teaWomanRadioButton))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(teaCollegeText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(teaDepartmentText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(teaRadioButton1)
                            .addComponent(teaRadioButton2)
                            .addComponent(teaRadioButton3)
                            .addComponent(teaRadioButton4)))
                    .addComponent(jLabel11))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teaPhoneText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teaInterestText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teaInfoAddButton)
                    .addComponent(teaInfoResetButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void teaInfoAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teaInfoAddButtonActionPerformed
        // TODO add your handling code here:
        //添加新老师信息
        try{
            teaInfoAddActionPerformed(evt);
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_teaInfoAddButtonActionPerformed

    private void teaManRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teaManRadioButtonActionPerformed
        // TODO add your handling code here:
        if(!this.teaManRadioButton.isSelected()){
            this.teaManRadioButton.setSelected(true);
        }
        this.teaWomanRadioButton.setSelected(false);
        teaSex = this.teaManRadioButton.getText();
        //System.out.println(teaSex);
    }//GEN-LAST:event_teaManRadioButtonActionPerformed

    private void teaIDTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teaIDTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teaIDTextActionPerformed

    private void teaNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teaNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teaNameTextActionPerformed

    private void teaDepartmentTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teaDepartmentTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teaDepartmentTextActionPerformed

    private void teaCollegeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teaCollegeTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teaCollegeTextActionPerformed

    private void teaInterestTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teaInterestTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teaInterestTextActionPerformed

    private void teaPhoneTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teaPhoneTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teaPhoneTextActionPerformed

    private void teaRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teaRadioButton1ActionPerformed
        // TODO add your handling code here:
        if(!this.teaRadioButton1.isSelected()){
            this.teaRadioButton1.setSelected(true);
        }
        this.teaRadioButton2.setSelected(false);
        this.teaRadioButton3.setSelected(false);
        this.teaRadioButton4.setSelected(false);
        teaType = this.teaRadioButton1.getText();
    }//GEN-LAST:event_teaRadioButton1ActionPerformed

    private void teaWomanRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teaWomanRadioButtonActionPerformed
        // TODO add your handling code here:
        if(!this.teaWomanRadioButton.isSelected()){
            this.teaWomanRadioButton.setSelected(true);
        }
        this.teaManRadioButton.setSelected(false);
        teaSex = this.teaWomanRadioButton.getText();
        //System.out.println(teaSex);
    }//GEN-LAST:event_teaWomanRadioButtonActionPerformed

    private void teaRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teaRadioButton2ActionPerformed
        // TODO add your handling code here:
        if(!this.teaRadioButton2.isSelected()){
            this.teaRadioButton2.setSelected(true);
        }
        this.teaRadioButton1.setSelected(false);
        this.teaRadioButton3.setSelected(false);
        this.teaRadioButton4.setSelected(false);
        teaType = this.teaRadioButton2.getText();
    }//GEN-LAST:event_teaRadioButton2ActionPerformed

    private void teaRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teaRadioButton3ActionPerformed
        // TODO add your handling code here:
        if(!this.teaRadioButton3.isSelected()){
            this.teaRadioButton3.setSelected(true);
        }
        this.teaRadioButton1.setSelected(false);
        this.teaRadioButton2.setSelected(false);
        this.teaRadioButton4.setSelected(false);
        teaType = this.teaRadioButton3.getText();
    }//GEN-LAST:event_teaRadioButton3ActionPerformed

    private void teaRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teaRadioButton4ActionPerformed
        // TODO add your handling code here:
        if(!this.teaRadioButton4.isSelected()){
            this.teaRadioButton4.setSelected(true);
        }
        this.teaRadioButton1.setSelected(false);
        this.teaRadioButton2.setSelected(false);
        this.teaRadioButton3.setSelected(false);
        teaType = this.teaRadioButton4.getText();
    }//GEN-LAST:event_teaRadioButton4ActionPerformed

    private void teaInfoResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teaInfoResetButtonActionPerformed
        // TODO add your handling code here:
        resetTeaInfo();//重置老师信息方法
    }//GEN-LAST:event_teaInfoResetButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JTextField teaCollegeText;
    private javax.swing.JTextField teaDepartmentText;
    private javax.swing.JTextField teaIDText;
    private javax.swing.JButton teaInfoAddButton;
    private javax.swing.JButton teaInfoResetButton;
    private javax.swing.JTextField teaInterestText;
    private javax.swing.JRadioButton teaManRadioButton;
    private javax.swing.JTextField teaNameText;
    private javax.swing.JTextField teaPhoneText;
    private javax.swing.JRadioButton teaRadioButton1;
    private javax.swing.JRadioButton teaRadioButton2;
    private javax.swing.JRadioButton teaRadioButton3;
    private javax.swing.JRadioButton teaRadioButton4;
    private javax.swing.JRadioButton teaWomanRadioButton;
    // End of variables declaration//GEN-END:variables

    private void teaInfoAddActionPerformed(ActionEvent evt) throws SQLException, Exception {//添加老师新信息
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        String teaID = this.teaIDText.getText();
        String teaName = this.teaNameText.getText();
        String teaCollege = this.teaCollegeText.getText();
        String teaDepartment = this.teaDepartmentText.getText();
        String teaPhone = this.teaPhoneText.getText();
        String teaRemark = this.teaInterestText.getText();
        if(StringUtil.isEmpty(teaID)){
            JOptionPane.showMessageDialog(null,"教工号不能为空！");
            return;
        }
        if(StringUtil.isEmpty(teaName)){
            JOptionPane.showMessageDialog(null,"姓名不能为空！");
            return;
        }
        if(StringUtil.isEmpty(teaCollege)){
            JOptionPane.showMessageDialog(null,"学院不能为空！");
            return;
        }
        if(StringUtil.isEmpty(teaDepartment)){
            JOptionPane.showMessageDialog(null,"系不能为空！");
            return;
        }
        if(StringUtil.isEmpty(teaPhone)){
            JOptionPane.showMessageDialog(null,"手机不能为空！");
            return;
        }
        if(teaID.length() != 11){
            JOptionPane.showMessageDialog(null,"教工号位数不为11位！");
            return;
        } 
        if(!StringUtil.isAllNumber(teaID)){
            JOptionPane.showMessageDialog(null,"教工号不为纯数字！");
            return;
        }
        if(teaPhone.length() != 11){
            JOptionPane.showMessageDialog(null,"手机号位数不为11位！");
            return;
        } 
        if(!StringUtil.isAllNumber(teaPhone)){
            JOptionPane.showMessageDialog(null,"手机号不为纯数字！");
            return;
        }
        Connection con = null;
        con = dbUtil.getConnection();
        if(teacherInfo.checkExist(con, teaID)){
            JOptionPane.showMessageDialog(null,"当前教工号已存在，请勿重复添加！");
            return;
        }
        Teacher teacher = new Teacher(teaID,teaName,teaSex,teaCollege,teaDepartment,teaType,teaPhone,teaRemark);
        try{
            con = dbUtil.getConnection();
            int result = teacherInfo.teacherInfoAdd(con, teacher);
            if(result == 1){
                JOptionPane.showMessageDialog(null,"老师添加成功！");
                resetTeaInfo();//重置老师信息所有栏
                return;
            }
            else{
                JOptionPane.showMessageDialog(null,"老师添加失败！");
                return;
            }
        }catch (Exception e)
        {
            e.printStackTrace();
        }
    }

    private void resetTeaInfo() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        this.teaIDText.setText("");
        this.teaNameText.setText("");
        this.teaCollegeText.setText("");
        this.teaDepartmentText.setText("");
        this.teaPhoneText.setText("");
        this.teaInterestText.setText("");
        this.teaManRadioButton.setSelected(true);
        this.teaWomanRadioButton.setSelected(false);
        teaSex = this.teaManRadioButton.getText();
        this.teaRadioButton1.setSelected(true);
        this.teaRadioButton2.setSelected(false);
        this.teaRadioButton3.setSelected(false);
        this.teaRadioButton4.setSelected(false);
        teaType = this.teaRadioButton1.getText();
    }
}
